spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myusername
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
