spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: always

logging:
  level:
    root: DEBUG
    com.example.transactionprocessor: DEBUG

cyber-source:
  org-id: akkapon_org_id_1731121879
  api-key:  bff118c4-0c0c-43e5-8800-1d1c807d0798
  api-secret: wtGtO1vpZ90w/UdaP69sIB3CZ528pxTTUYWhtfTyY1U=