spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: always

logging:
  level:
    root: DEBUG
    com.example.transactionprocessor: DEBUG
