/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.ActionDecisionManagerCase200ResponseEmbeddedCaptureLinksSelf;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The link to the GET method to the capture transaction if the capture is called. 
 */
@JsonPropertyOrder({
  ActionDecisionManagerCase200ResponseEmbeddedCaptureLinks.JSON_PROPERTY_SELF
})
@JsonTypeName("actionDecisionManagerCase_200_response__embedded_capture__links")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class ActionDecisionManagerCase200ResponseEmbeddedCaptureLinks {
  public static final String JSON_PROPERTY_SELF = "self";
  private ActionDecisionManagerCase200ResponseEmbeddedCaptureLinksSelf self;

  public ActionDecisionManagerCase200ResponseEmbeddedCaptureLinks() {
  }

  public ActionDecisionManagerCase200ResponseEmbeddedCaptureLinks self(ActionDecisionManagerCase200ResponseEmbeddedCaptureLinksSelf self) {
    
    this.self = self;
    return this;
  }

  /**
   * Get self
   * @return self
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActionDecisionManagerCase200ResponseEmbeddedCaptureLinksSelf getSelf() {
    return self;
  }


  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelf(ActionDecisionManagerCase200ResponseEmbeddedCaptureLinksSelf self) {
    this.self = self;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionDecisionManagerCase200ResponseEmbeddedCaptureLinks actionDecisionManagerCase200ResponseEmbeddedCaptureLinks = (ActionDecisionManagerCase200ResponseEmbeddedCaptureLinks) o;
    return Objects.equals(this.self, actionDecisionManagerCase200ResponseEmbeddedCaptureLinks.self);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionDecisionManagerCase200ResponseEmbeddedCaptureLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

