/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CreatePaymentRequestTravelInformationLodgingRoomInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreatePaymentRequestTravelInformationLodging
 */
@JsonPropertyOrder({
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_CHECK_IN_DATE,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_CHECK_OUT_DATE,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_ROOM,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_SMOKING_PREFERENCE,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_NUMBER_OF_ROOMS,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_NUMBER_OF_GUESTS,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_ROOM_BED_TYPE,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_ROOM_TAX_TYPE,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_ROOM_RATE_TYPE,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_GUEST_NAME,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_CUSTOMER_SERVICE_PHONE_NUMBER,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_CORPORATE_CLIENT_CODE,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_ADDITIONAL_DISCOUNT_AMOUNT,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_ROOM_LOCATION,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_SPECIAL_PROGRAM_CODE,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_TOTAL_TAX_AMOUNT,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_PREPAID_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_FOOD_AND_BEVERAGE_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_ROOM_TAX_AMOUNT,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_ADJUSTMENT_AMOUNT,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_PHONE_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_RESTAURANT_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_ROOM_SERVICE_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_MINI_BAR_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_LAUNDRY_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_MISCELLANEOUS_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_GIFT_SHOP_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_MOVIE_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_HEALTH_CLUB_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_VALET_PARKING_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_CASH_DISBURSEMENT_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_NON_ROOM_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_BUSINESS_CENTER_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_LOUNGE_BAR_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_TRANSPORTATION_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_GRATUITY_AMOUNT,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_CONFERENCE_ROOM_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_AUDIO_VISUAL_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_BANQUEST_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_NON_ROOM_TAX_AMOUNT,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_EARLY_CHECK_OUT_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_INTERNET_ACCESS_COST,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_NAME,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_HOTEL_NAME,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_CHECK_IN_DATE_TIME,
  CreatePaymentRequestTravelInformationLodging.JSON_PROPERTY_CHECK_OUT_DATE_TIME
})
@JsonTypeName("createPayment_request_travelInformation_lodging")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class CreatePaymentRequestTravelInformationLodging {
  public static final String JSON_PROPERTY_CHECK_IN_DATE = "checkInDate";
  private String checkInDate;

  public static final String JSON_PROPERTY_CHECK_OUT_DATE = "checkOutDate";
  private String checkOutDate;

  public static final String JSON_PROPERTY_ROOM = "room";
  private List<CreatePaymentRequestTravelInformationLodgingRoomInner> room = new ArrayList<>();

  public static final String JSON_PROPERTY_SMOKING_PREFERENCE = "smokingPreference";
  private String smokingPreference;

  public static final String JSON_PROPERTY_NUMBER_OF_ROOMS = "numberOfRooms";
  private Integer numberOfRooms;

  public static final String JSON_PROPERTY_NUMBER_OF_GUESTS = "numberOfGuests";
  private Integer numberOfGuests;

  public static final String JSON_PROPERTY_ROOM_BED_TYPE = "roomBedType";
  private String roomBedType;

  public static final String JSON_PROPERTY_ROOM_TAX_TYPE = "roomTaxType";
  private String roomTaxType;

  public static final String JSON_PROPERTY_ROOM_RATE_TYPE = "roomRateType";
  private String roomRateType;

  public static final String JSON_PROPERTY_GUEST_NAME = "guestName";
  private String guestName;

  public static final String JSON_PROPERTY_CUSTOMER_SERVICE_PHONE_NUMBER = "customerServicePhoneNumber";
  private String customerServicePhoneNumber;

  public static final String JSON_PROPERTY_CORPORATE_CLIENT_CODE = "corporateClientCode";
  private String corporateClientCode;

  public static final String JSON_PROPERTY_ADDITIONAL_DISCOUNT_AMOUNT = "additionalDiscountAmount";
  private String additionalDiscountAmount;

  public static final String JSON_PROPERTY_ROOM_LOCATION = "roomLocation";
  private String roomLocation;

  public static final String JSON_PROPERTY_SPECIAL_PROGRAM_CODE = "specialProgramCode";
  private String specialProgramCode;

  public static final String JSON_PROPERTY_TOTAL_TAX_AMOUNT = "totalTaxAmount";
  private String totalTaxAmount;

  public static final String JSON_PROPERTY_PREPAID_COST = "prepaidCost";
  private String prepaidCost;

  public static final String JSON_PROPERTY_FOOD_AND_BEVERAGE_COST = "foodAndBeverageCost";
  private String foodAndBeverageCost;

  public static final String JSON_PROPERTY_ROOM_TAX_AMOUNT = "roomTaxAmount";
  private String roomTaxAmount;

  public static final String JSON_PROPERTY_ADJUSTMENT_AMOUNT = "adjustmentAmount";
  private String adjustmentAmount;

  public static final String JSON_PROPERTY_PHONE_COST = "phoneCost";
  private String phoneCost;

  public static final String JSON_PROPERTY_RESTAURANT_COST = "restaurantCost";
  private String restaurantCost;

  public static final String JSON_PROPERTY_ROOM_SERVICE_COST = "roomServiceCost";
  private String roomServiceCost;

  public static final String JSON_PROPERTY_MINI_BAR_COST = "miniBarCost";
  private String miniBarCost;

  public static final String JSON_PROPERTY_LAUNDRY_COST = "laundryCost";
  private String laundryCost;

  public static final String JSON_PROPERTY_MISCELLANEOUS_COST = "miscellaneousCost";
  private String miscellaneousCost;

  public static final String JSON_PROPERTY_GIFT_SHOP_COST = "giftShopCost";
  private String giftShopCost;

  public static final String JSON_PROPERTY_MOVIE_COST = "movieCost";
  private String movieCost;

  public static final String JSON_PROPERTY_HEALTH_CLUB_COST = "healthClubCost";
  private String healthClubCost;

  public static final String JSON_PROPERTY_VALET_PARKING_COST = "valetParkingCost";
  private String valetParkingCost;

  public static final String JSON_PROPERTY_CASH_DISBURSEMENT_COST = "cashDisbursementCost";
  private String cashDisbursementCost;

  public static final String JSON_PROPERTY_NON_ROOM_COST = "nonRoomCost";
  private String nonRoomCost;

  public static final String JSON_PROPERTY_BUSINESS_CENTER_COST = "businessCenterCost";
  private String businessCenterCost;

  public static final String JSON_PROPERTY_LOUNGE_BAR_COST = "loungeBarCost";
  private String loungeBarCost;

  public static final String JSON_PROPERTY_TRANSPORTATION_COST = "transportationCost";
  private String transportationCost;

  public static final String JSON_PROPERTY_GRATUITY_AMOUNT = "gratuityAmount";
  private String gratuityAmount;

  public static final String JSON_PROPERTY_CONFERENCE_ROOM_COST = "conferenceRoomCost";
  private String conferenceRoomCost;

  public static final String JSON_PROPERTY_AUDIO_VISUAL_COST = "audioVisualCost";
  private String audioVisualCost;

  public static final String JSON_PROPERTY_BANQUEST_COST = "banquestCost";
  private String banquestCost;

  public static final String JSON_PROPERTY_NON_ROOM_TAX_AMOUNT = "nonRoomTaxAmount";
  private String nonRoomTaxAmount;

  public static final String JSON_PROPERTY_EARLY_CHECK_OUT_COST = "earlyCheckOutCost";
  private String earlyCheckOutCost;

  public static final String JSON_PROPERTY_INTERNET_ACCESS_COST = "internetAccessCost";
  private String internetAccessCost;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_HOTEL_NAME = "hotelName";
  private String hotelName;

  public static final String JSON_PROPERTY_CHECK_IN_DATE_TIME = "checkInDateTime";
  private String checkInDateTime;

  public static final String JSON_PROPERTY_CHECK_OUT_DATE_TIME = "checkOutDateTime";
  private String checkOutDateTime;

  public CreatePaymentRequestTravelInformationLodging() {
  }

  public CreatePaymentRequestTravelInformationLodging checkInDate(String checkInDate) {
    
    this.checkInDate = checkInDate;
    return this;
  }

  /**
   * Date on which the guest checked in. In the case of a no-show or a reservation, the scheduled arrival date. Format: &#x60;MMDDYY&#x60;. For best interchange rates, make sure it is a valid date. 
   * @return checkInDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_IN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCheckInDate() {
    return checkInDate;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_IN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckInDate(String checkInDate) {
    this.checkInDate = checkInDate;
  }

  public CreatePaymentRequestTravelInformationLodging checkOutDate(String checkOutDate) {
    
    this.checkOutDate = checkOutDate;
    return this;
  }

  /**
   * Date on which the guest checked out. Format: &#x60;MMDDYY&#x60;. For best interchange rates, make sure it is a valid date. 
   * @return checkOutDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_OUT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCheckOutDate() {
    return checkOutDate;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_OUT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckOutDate(String checkOutDate) {
    this.checkOutDate = checkOutDate;
  }

  public CreatePaymentRequestTravelInformationLodging room(List<CreatePaymentRequestTravelInformationLodgingRoomInner> room) {
    
    this.room = room;
    return this;
  }

  public CreatePaymentRequestTravelInformationLodging addRoomItem(CreatePaymentRequestTravelInformationLodgingRoomInner roomItem) {
    if (this.room == null) {
      this.room = new ArrayList<>();
    }
    this.room.add(roomItem);
    return this;
  }

  /**
   * The object containing the number of nights and the daily rate that applies for that no of nights. 
   * @return room
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CreatePaymentRequestTravelInformationLodgingRoomInner> getRoom() {
    return room;
  }


  @JsonProperty(JSON_PROPERTY_ROOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoom(List<CreatePaymentRequestTravelInformationLodgingRoomInner> room) {
    this.room = room;
  }

  public CreatePaymentRequestTravelInformationLodging smokingPreference(String smokingPreference) {
    
    this.smokingPreference = smokingPreference;
    return this;
  }

  /**
   * Smoking preference of the guest. Possible values: - &#x60;Y&#x60;: smoking room - &#x60;N&#x60;: non-smoking room 
   * @return smokingPreference
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SMOKING_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSmokingPreference() {
    return smokingPreference;
  }


  @JsonProperty(JSON_PROPERTY_SMOKING_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmokingPreference(String smokingPreference) {
    this.smokingPreference = smokingPreference;
  }

  public CreatePaymentRequestTravelInformationLodging numberOfRooms(Integer numberOfRooms) {
    
    this.numberOfRooms = numberOfRooms;
    return this;
  }

  /**
   * Number of rooms booked by the cardholder. 
   * minimum: 1
   * maximum: 99
   * @return numberOfRooms
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_ROOMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumberOfRooms() {
    return numberOfRooms;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_OF_ROOMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberOfRooms(Integer numberOfRooms) {
    this.numberOfRooms = numberOfRooms;
  }

  public CreatePaymentRequestTravelInformationLodging numberOfGuests(Integer numberOfGuests) {
    
    this.numberOfGuests = numberOfGuests;
    return this;
  }

  /**
   * Number of guests staying in the room. 
   * minimum: 1
   * maximum: 99
   * @return numberOfGuests
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_GUESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumberOfGuests() {
    return numberOfGuests;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_OF_GUESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberOfGuests(Integer numberOfGuests) {
    this.numberOfGuests = numberOfGuests;
  }

  public CreatePaymentRequestTravelInformationLodging roomBedType(String roomBedType) {
    
    this.roomBedType = roomBedType;
    return this;
  }

  /**
   * Type of room, such as queen, king, or two doubles. 
   * @return roomBedType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROOM_BED_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRoomBedType() {
    return roomBedType;
  }


  @JsonProperty(JSON_PROPERTY_ROOM_BED_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoomBedType(String roomBedType) {
    this.roomBedType = roomBedType;
  }

  public CreatePaymentRequestTravelInformationLodging roomTaxType(String roomTaxType) {
    
    this.roomTaxType = roomTaxType;
    return this;
  }

  /**
   * Type of tax, such as tourist or hotel. 
   * @return roomTaxType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROOM_TAX_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRoomTaxType() {
    return roomTaxType;
  }


  @JsonProperty(JSON_PROPERTY_ROOM_TAX_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoomTaxType(String roomTaxType) {
    this.roomTaxType = roomTaxType;
  }

  public CreatePaymentRequestTravelInformationLodging roomRateType(String roomRateType) {
    
    this.roomRateType = roomRateType;
    return this;
  }

  /**
   * Type of rate, such as corporate or senior citizen. 
   * @return roomRateType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROOM_RATE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRoomRateType() {
    return roomRateType;
  }


  @JsonProperty(JSON_PROPERTY_ROOM_RATE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoomRateType(String roomRateType) {
    this.roomRateType = roomRateType;
  }

  public CreatePaymentRequestTravelInformationLodging guestName(String guestName) {
    
    this.guestName = guestName;
    return this;
  }

  /**
   * Name of the guest under which the room is reserved. 
   * @return guestName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GUEST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGuestName() {
    return guestName;
  }


  @JsonProperty(JSON_PROPERTY_GUEST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGuestName(String guestName) {
    this.guestName = guestName;
  }

  public CreatePaymentRequestTravelInformationLodging customerServicePhoneNumber(String customerServicePhoneNumber) {
    
    this.customerServicePhoneNumber = customerServicePhoneNumber;
    return this;
  }

  /**
   * Your toll-free customer service phone number. 
   * @return customerServicePhoneNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER_SERVICE_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerServicePhoneNumber() {
    return customerServicePhoneNumber;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_SERVICE_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerServicePhoneNumber(String customerServicePhoneNumber) {
    this.customerServicePhoneNumber = customerServicePhoneNumber;
  }

  public CreatePaymentRequestTravelInformationLodging corporateClientCode(String corporateClientCode) {
    
    this.corporateClientCode = corporateClientCode;
    return this;
  }

  /**
   * Code assigned to a business. You can use this code to identify corporate rates and discounts for guests. 
   * @return corporateClientCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CORPORATE_CLIENT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCorporateClientCode() {
    return corporateClientCode;
  }


  @JsonProperty(JSON_PROPERTY_CORPORATE_CLIENT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCorporateClientCode(String corporateClientCode) {
    this.corporateClientCode = corporateClientCode;
  }

  public CreatePaymentRequestTravelInformationLodging additionalDiscountAmount(String additionalDiscountAmount) {
    
    this.additionalDiscountAmount = additionalDiscountAmount;
    return this;
  }

  /**
   * Amount of an additional coupon or discount. 
   * @return additionalDiscountAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_DISCOUNT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalDiscountAmount() {
    return additionalDiscountAmount;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_DISCOUNT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalDiscountAmount(String additionalDiscountAmount) {
    this.additionalDiscountAmount = additionalDiscountAmount;
  }

  public CreatePaymentRequestTravelInformationLodging roomLocation(String roomLocation) {
    
    this.roomLocation = roomLocation;
    return this;
  }

  /**
   * Location of room, such as lake view or ocean view. 
   * @return roomLocation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROOM_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRoomLocation() {
    return roomLocation;
  }


  @JsonProperty(JSON_PROPERTY_ROOM_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoomLocation(String roomLocation) {
    this.roomLocation = roomLocation;
  }

  public CreatePaymentRequestTravelInformationLodging specialProgramCode(String specialProgramCode) {
    
    this.specialProgramCode = specialProgramCode;
    return this;
  }

  /**
   * Code that identifies special circumstances. Possible values: - &#x60;1&#x60;: lodging (default) - &#x60;2&#x60;: no show reservation - &#x60;3&#x60;: advanced deposit 
   * @return specialProgramCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPECIAL_PROGRAM_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSpecialProgramCode() {
    return specialProgramCode;
  }


  @JsonProperty(JSON_PROPERTY_SPECIAL_PROGRAM_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecialProgramCode(String specialProgramCode) {
    this.specialProgramCode = specialProgramCode;
  }

  public CreatePaymentRequestTravelInformationLodging totalTaxAmount(String totalTaxAmount) {
    
    this.totalTaxAmount = totalTaxAmount;
    return this;
  }

  /**
   * Total tax amount. 
   * @return totalTaxAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_TAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTotalTaxAmount() {
    return totalTaxAmount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_TAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalTaxAmount(String totalTaxAmount) {
    this.totalTaxAmount = totalTaxAmount;
  }

  public CreatePaymentRequestTravelInformationLodging prepaidCost(String prepaidCost) {
    
    this.prepaidCost = prepaidCost;
    return this;
  }

  /**
   * Prepaid amount, such as a deposit. 
   * @return prepaidCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREPAID_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrepaidCost() {
    return prepaidCost;
  }


  @JsonProperty(JSON_PROPERTY_PREPAID_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrepaidCost(String prepaidCost) {
    this.prepaidCost = prepaidCost;
  }

  public CreatePaymentRequestTravelInformationLodging foodAndBeverageCost(String foodAndBeverageCost) {
    
    this.foodAndBeverageCost = foodAndBeverageCost;
    return this;
  }

  /**
   * Cost for all food and beverages. 
   * @return foodAndBeverageCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOOD_AND_BEVERAGE_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFoodAndBeverageCost() {
    return foodAndBeverageCost;
  }


  @JsonProperty(JSON_PROPERTY_FOOD_AND_BEVERAGE_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFoodAndBeverageCost(String foodAndBeverageCost) {
    this.foodAndBeverageCost = foodAndBeverageCost;
  }

  public CreatePaymentRequestTravelInformationLodging roomTaxAmount(String roomTaxAmount) {
    
    this.roomTaxAmount = roomTaxAmount;
    return this;
  }

  /**
   * Total tax for the room. 
   * @return roomTaxAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROOM_TAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRoomTaxAmount() {
    return roomTaxAmount;
  }


  @JsonProperty(JSON_PROPERTY_ROOM_TAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoomTaxAmount(String roomTaxAmount) {
    this.roomTaxAmount = roomTaxAmount;
  }

  public CreatePaymentRequestTravelInformationLodging adjustmentAmount(String adjustmentAmount) {
    
    this.adjustmentAmount = adjustmentAmount;
    return this;
  }

  /**
   * Adjusted amount charged in addition to the reservation amount after the stay is complete. 
   * @return adjustmentAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADJUSTMENT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdjustmentAmount() {
    return adjustmentAmount;
  }


  @JsonProperty(JSON_PROPERTY_ADJUSTMENT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdjustmentAmount(String adjustmentAmount) {
    this.adjustmentAmount = adjustmentAmount;
  }

  public CreatePaymentRequestTravelInformationLodging phoneCost(String phoneCost) {
    
    this.phoneCost = phoneCost;
    return this;
  }

  /**
   * Cost of telephone services. 
   * @return phoneCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhoneCost() {
    return phoneCost;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneCost(String phoneCost) {
    this.phoneCost = phoneCost;
  }

  public CreatePaymentRequestTravelInformationLodging restaurantCost(String restaurantCost) {
    
    this.restaurantCost = restaurantCost;
    return this;
  }

  /**
   * Cost of restaurant purchases 
   * @return restaurantCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESTAURANT_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRestaurantCost() {
    return restaurantCost;
  }


  @JsonProperty(JSON_PROPERTY_RESTAURANT_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestaurantCost(String restaurantCost) {
    this.restaurantCost = restaurantCost;
  }

  public CreatePaymentRequestTravelInformationLodging roomServiceCost(String roomServiceCost) {
    
    this.roomServiceCost = roomServiceCost;
    return this;
  }

  /**
   * Cost of room service. 
   * @return roomServiceCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROOM_SERVICE_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRoomServiceCost() {
    return roomServiceCost;
  }


  @JsonProperty(JSON_PROPERTY_ROOM_SERVICE_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoomServiceCost(String roomServiceCost) {
    this.roomServiceCost = roomServiceCost;
  }

  public CreatePaymentRequestTravelInformationLodging miniBarCost(String miniBarCost) {
    
    this.miniBarCost = miniBarCost;
    return this;
  }

  /**
   * Cost of mini-bar purchases. 
   * @return miniBarCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MINI_BAR_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMiniBarCost() {
    return miniBarCost;
  }


  @JsonProperty(JSON_PROPERTY_MINI_BAR_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMiniBarCost(String miniBarCost) {
    this.miniBarCost = miniBarCost;
  }

  public CreatePaymentRequestTravelInformationLodging laundryCost(String laundryCost) {
    
    this.laundryCost = laundryCost;
    return this;
  }

  /**
   * Cost of laundry services. 
   * @return laundryCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAUNDRY_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLaundryCost() {
    return laundryCost;
  }


  @JsonProperty(JSON_PROPERTY_LAUNDRY_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLaundryCost(String laundryCost) {
    this.laundryCost = laundryCost;
  }

  public CreatePaymentRequestTravelInformationLodging miscellaneousCost(String miscellaneousCost) {
    
    this.miscellaneousCost = miscellaneousCost;
    return this;
  }

  /**
   * Miscellaneous costs. 
   * @return miscellaneousCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MISCELLANEOUS_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMiscellaneousCost() {
    return miscellaneousCost;
  }


  @JsonProperty(JSON_PROPERTY_MISCELLANEOUS_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMiscellaneousCost(String miscellaneousCost) {
    this.miscellaneousCost = miscellaneousCost;
  }

  public CreatePaymentRequestTravelInformationLodging giftShopCost(String giftShopCost) {
    
    this.giftShopCost = giftShopCost;
    return this;
  }

  /**
   * Cost of gift shop purchases. 
   * @return giftShopCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GIFT_SHOP_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGiftShopCost() {
    return giftShopCost;
  }


  @JsonProperty(JSON_PROPERTY_GIFT_SHOP_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGiftShopCost(String giftShopCost) {
    this.giftShopCost = giftShopCost;
  }

  public CreatePaymentRequestTravelInformationLodging movieCost(String movieCost) {
    
    this.movieCost = movieCost;
    return this;
  }

  /**
   * Cost of movies. 
   * @return movieCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOVIE_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMovieCost() {
    return movieCost;
  }


  @JsonProperty(JSON_PROPERTY_MOVIE_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovieCost(String movieCost) {
    this.movieCost = movieCost;
  }

  public CreatePaymentRequestTravelInformationLodging healthClubCost(String healthClubCost) {
    
    this.healthClubCost = healthClubCost;
    return this;
  }

  /**
   * Cost of health club services. 
   * @return healthClubCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEALTH_CLUB_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHealthClubCost() {
    return healthClubCost;
  }


  @JsonProperty(JSON_PROPERTY_HEALTH_CLUB_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHealthClubCost(String healthClubCost) {
    this.healthClubCost = healthClubCost;
  }

  public CreatePaymentRequestTravelInformationLodging valetParkingCost(String valetParkingCost) {
    
    this.valetParkingCost = valetParkingCost;
    return this;
  }

  /**
   * Cost of valet parking services. 
   * @return valetParkingCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALET_PARKING_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValetParkingCost() {
    return valetParkingCost;
  }


  @JsonProperty(JSON_PROPERTY_VALET_PARKING_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValetParkingCost(String valetParkingCost) {
    this.valetParkingCost = valetParkingCost;
  }

  public CreatePaymentRequestTravelInformationLodging cashDisbursementCost(String cashDisbursementCost) {
    
    this.cashDisbursementCost = cashDisbursementCost;
    return this;
  }

  /**
   * Cost of the cash that was disbursed plus any associated service fees 
   * @return cashDisbursementCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CASH_DISBURSEMENT_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCashDisbursementCost() {
    return cashDisbursementCost;
  }


  @JsonProperty(JSON_PROPERTY_CASH_DISBURSEMENT_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCashDisbursementCost(String cashDisbursementCost) {
    this.cashDisbursementCost = cashDisbursementCost;
  }

  public CreatePaymentRequestTravelInformationLodging nonRoomCost(String nonRoomCost) {
    
    this.nonRoomCost = nonRoomCost;
    return this;
  }

  /**
   * Cost of non-room purchases, such as meals and gifts. 
   * @return nonRoomCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NON_ROOM_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNonRoomCost() {
    return nonRoomCost;
  }


  @JsonProperty(JSON_PROPERTY_NON_ROOM_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNonRoomCost(String nonRoomCost) {
    this.nonRoomCost = nonRoomCost;
  }

  public CreatePaymentRequestTravelInformationLodging businessCenterCost(String businessCenterCost) {
    
    this.businessCenterCost = businessCenterCost;
    return this;
  }

  /**
   * Cost of business center services. 
   * @return businessCenterCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUSINESS_CENTER_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBusinessCenterCost() {
    return businessCenterCost;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_CENTER_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessCenterCost(String businessCenterCost) {
    this.businessCenterCost = businessCenterCost;
  }

  public CreatePaymentRequestTravelInformationLodging loungeBarCost(String loungeBarCost) {
    
    this.loungeBarCost = loungeBarCost;
    return this;
  }

  /**
   * Cost of lounge and bar purchases. 
   * @return loungeBarCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOUNGE_BAR_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoungeBarCost() {
    return loungeBarCost;
  }


  @JsonProperty(JSON_PROPERTY_LOUNGE_BAR_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoungeBarCost(String loungeBarCost) {
    this.loungeBarCost = loungeBarCost;
  }

  public CreatePaymentRequestTravelInformationLodging transportationCost(String transportationCost) {
    
    this.transportationCost = transportationCost;
    return this;
  }

  /**
   * Cost of transportation services. 
   * @return transportationCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSPORTATION_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransportationCost() {
    return transportationCost;
  }


  @JsonProperty(JSON_PROPERTY_TRANSPORTATION_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransportationCost(String transportationCost) {
    this.transportationCost = transportationCost;
  }

  public CreatePaymentRequestTravelInformationLodging gratuityAmount(String gratuityAmount) {
    
    this.gratuityAmount = gratuityAmount;
    return this;
  }

  /**
   * Gratuity. 
   * @return gratuityAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GRATUITY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGratuityAmount() {
    return gratuityAmount;
  }


  @JsonProperty(JSON_PROPERTY_GRATUITY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGratuityAmount(String gratuityAmount) {
    this.gratuityAmount = gratuityAmount;
  }

  public CreatePaymentRequestTravelInformationLodging conferenceRoomCost(String conferenceRoomCost) {
    
    this.conferenceRoomCost = conferenceRoomCost;
    return this;
  }

  /**
   * Cost of conference room services. 
   * @return conferenceRoomCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFERENCE_ROOM_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConferenceRoomCost() {
    return conferenceRoomCost;
  }


  @JsonProperty(JSON_PROPERTY_CONFERENCE_ROOM_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConferenceRoomCost(String conferenceRoomCost) {
    this.conferenceRoomCost = conferenceRoomCost;
  }

  public CreatePaymentRequestTravelInformationLodging audioVisualCost(String audioVisualCost) {
    
    this.audioVisualCost = audioVisualCost;
    return this;
  }

  /**
   * Cost of audio visual services. 
   * @return audioVisualCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUDIO_VISUAL_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAudioVisualCost() {
    return audioVisualCost;
  }


  @JsonProperty(JSON_PROPERTY_AUDIO_VISUAL_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAudioVisualCost(String audioVisualCost) {
    this.audioVisualCost = audioVisualCost;
  }

  public CreatePaymentRequestTravelInformationLodging banquestCost(String banquestCost) {
    
    this.banquestCost = banquestCost;
    return this;
  }

  /**
   * Cost of banquet services. 
   * @return banquestCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BANQUEST_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBanquestCost() {
    return banquestCost;
  }


  @JsonProperty(JSON_PROPERTY_BANQUEST_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBanquestCost(String banquestCost) {
    this.banquestCost = banquestCost;
  }

  public CreatePaymentRequestTravelInformationLodging nonRoomTaxAmount(String nonRoomTaxAmount) {
    
    this.nonRoomTaxAmount = nonRoomTaxAmount;
    return this;
  }

  /**
   * Tax on non-room purchases. 
   * @return nonRoomTaxAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NON_ROOM_TAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNonRoomTaxAmount() {
    return nonRoomTaxAmount;
  }


  @JsonProperty(JSON_PROPERTY_NON_ROOM_TAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNonRoomTaxAmount(String nonRoomTaxAmount) {
    this.nonRoomTaxAmount = nonRoomTaxAmount;
  }

  public CreatePaymentRequestTravelInformationLodging earlyCheckOutCost(String earlyCheckOutCost) {
    
    this.earlyCheckOutCost = earlyCheckOutCost;
    return this;
  }

  /**
   * Service fee for early departure. 
   * @return earlyCheckOutCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EARLY_CHECK_OUT_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEarlyCheckOutCost() {
    return earlyCheckOutCost;
  }


  @JsonProperty(JSON_PROPERTY_EARLY_CHECK_OUT_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEarlyCheckOutCost(String earlyCheckOutCost) {
    this.earlyCheckOutCost = earlyCheckOutCost;
  }

  public CreatePaymentRequestTravelInformationLodging internetAccessCost(String internetAccessCost) {
    
    this.internetAccessCost = internetAccessCost;
    return this;
  }

  /**
   * Cost of Internet access. 
   * @return internetAccessCost
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERNET_ACCESS_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInternetAccessCost() {
    return internetAccessCost;
  }


  @JsonProperty(JSON_PROPERTY_INTERNET_ACCESS_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInternetAccessCost(String internetAccessCost) {
    this.internetAccessCost = internetAccessCost;
  }

  public CreatePaymentRequestTravelInformationLodging name(String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Name of the hotel for which the reservation is for. Mandatory in case the merchant&#39;s business type is Hotel. 
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  public CreatePaymentRequestTravelInformationLodging hotelName(String hotelName) {
    
    this.hotelName = hotelName;
    return this;
  }

  /**
   * The name of the hotel for which the reservation was made. 
   * @return hotelName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HOTEL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHotelName() {
    return hotelName;
  }


  @JsonProperty(JSON_PROPERTY_HOTEL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHotelName(String hotelName) {
    this.hotelName = hotelName;
  }

  public CreatePaymentRequestTravelInformationLodging checkInDateTime(String checkInDateTime) {
    
    this.checkInDateTime = checkInDateTime;
    return this;
  }

  /**
   * The date of the check-in in GMT+8 offset. 
   * @return checkInDateTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_IN_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCheckInDateTime() {
    return checkInDateTime;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_IN_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckInDateTime(String checkInDateTime) {
    this.checkInDateTime = checkInDateTime;
  }

  public CreatePaymentRequestTravelInformationLodging checkOutDateTime(String checkOutDateTime) {
    
    this.checkOutDateTime = checkOutDateTime;
    return this;
  }

  /**
   * The date of the check-out in GMT+8 offset. 
   * @return checkOutDateTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_OUT_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCheckOutDateTime() {
    return checkOutDateTime;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_OUT_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckOutDateTime(String checkOutDateTime) {
    this.checkOutDateTime = checkOutDateTime;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePaymentRequestTravelInformationLodging createPaymentRequestTravelInformationLodging = (CreatePaymentRequestTravelInformationLodging) o;
    return Objects.equals(this.checkInDate, createPaymentRequestTravelInformationLodging.checkInDate) &&
        Objects.equals(this.checkOutDate, createPaymentRequestTravelInformationLodging.checkOutDate) &&
        Objects.equals(this.room, createPaymentRequestTravelInformationLodging.room) &&
        Objects.equals(this.smokingPreference, createPaymentRequestTravelInformationLodging.smokingPreference) &&
        Objects.equals(this.numberOfRooms, createPaymentRequestTravelInformationLodging.numberOfRooms) &&
        Objects.equals(this.numberOfGuests, createPaymentRequestTravelInformationLodging.numberOfGuests) &&
        Objects.equals(this.roomBedType, createPaymentRequestTravelInformationLodging.roomBedType) &&
        Objects.equals(this.roomTaxType, createPaymentRequestTravelInformationLodging.roomTaxType) &&
        Objects.equals(this.roomRateType, createPaymentRequestTravelInformationLodging.roomRateType) &&
        Objects.equals(this.guestName, createPaymentRequestTravelInformationLodging.guestName) &&
        Objects.equals(this.customerServicePhoneNumber, createPaymentRequestTravelInformationLodging.customerServicePhoneNumber) &&
        Objects.equals(this.corporateClientCode, createPaymentRequestTravelInformationLodging.corporateClientCode) &&
        Objects.equals(this.additionalDiscountAmount, createPaymentRequestTravelInformationLodging.additionalDiscountAmount) &&
        Objects.equals(this.roomLocation, createPaymentRequestTravelInformationLodging.roomLocation) &&
        Objects.equals(this.specialProgramCode, createPaymentRequestTravelInformationLodging.specialProgramCode) &&
        Objects.equals(this.totalTaxAmount, createPaymentRequestTravelInformationLodging.totalTaxAmount) &&
        Objects.equals(this.prepaidCost, createPaymentRequestTravelInformationLodging.prepaidCost) &&
        Objects.equals(this.foodAndBeverageCost, createPaymentRequestTravelInformationLodging.foodAndBeverageCost) &&
        Objects.equals(this.roomTaxAmount, createPaymentRequestTravelInformationLodging.roomTaxAmount) &&
        Objects.equals(this.adjustmentAmount, createPaymentRequestTravelInformationLodging.adjustmentAmount) &&
        Objects.equals(this.phoneCost, createPaymentRequestTravelInformationLodging.phoneCost) &&
        Objects.equals(this.restaurantCost, createPaymentRequestTravelInformationLodging.restaurantCost) &&
        Objects.equals(this.roomServiceCost, createPaymentRequestTravelInformationLodging.roomServiceCost) &&
        Objects.equals(this.miniBarCost, createPaymentRequestTravelInformationLodging.miniBarCost) &&
        Objects.equals(this.laundryCost, createPaymentRequestTravelInformationLodging.laundryCost) &&
        Objects.equals(this.miscellaneousCost, createPaymentRequestTravelInformationLodging.miscellaneousCost) &&
        Objects.equals(this.giftShopCost, createPaymentRequestTravelInformationLodging.giftShopCost) &&
        Objects.equals(this.movieCost, createPaymentRequestTravelInformationLodging.movieCost) &&
        Objects.equals(this.healthClubCost, createPaymentRequestTravelInformationLodging.healthClubCost) &&
        Objects.equals(this.valetParkingCost, createPaymentRequestTravelInformationLodging.valetParkingCost) &&
        Objects.equals(this.cashDisbursementCost, createPaymentRequestTravelInformationLodging.cashDisbursementCost) &&
        Objects.equals(this.nonRoomCost, createPaymentRequestTravelInformationLodging.nonRoomCost) &&
        Objects.equals(this.businessCenterCost, createPaymentRequestTravelInformationLodging.businessCenterCost) &&
        Objects.equals(this.loungeBarCost, createPaymentRequestTravelInformationLodging.loungeBarCost) &&
        Objects.equals(this.transportationCost, createPaymentRequestTravelInformationLodging.transportationCost) &&
        Objects.equals(this.gratuityAmount, createPaymentRequestTravelInformationLodging.gratuityAmount) &&
        Objects.equals(this.conferenceRoomCost, createPaymentRequestTravelInformationLodging.conferenceRoomCost) &&
        Objects.equals(this.audioVisualCost, createPaymentRequestTravelInformationLodging.audioVisualCost) &&
        Objects.equals(this.banquestCost, createPaymentRequestTravelInformationLodging.banquestCost) &&
        Objects.equals(this.nonRoomTaxAmount, createPaymentRequestTravelInformationLodging.nonRoomTaxAmount) &&
        Objects.equals(this.earlyCheckOutCost, createPaymentRequestTravelInformationLodging.earlyCheckOutCost) &&
        Objects.equals(this.internetAccessCost, createPaymentRequestTravelInformationLodging.internetAccessCost) &&
        Objects.equals(this.name, createPaymentRequestTravelInformationLodging.name) &&
        Objects.equals(this.hotelName, createPaymentRequestTravelInformationLodging.hotelName) &&
        Objects.equals(this.checkInDateTime, createPaymentRequestTravelInformationLodging.checkInDateTime) &&
        Objects.equals(this.checkOutDateTime, createPaymentRequestTravelInformationLodging.checkOutDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkInDate, checkOutDate, room, smokingPreference, numberOfRooms, numberOfGuests, roomBedType, roomTaxType, roomRateType, guestName, customerServicePhoneNumber, corporateClientCode, additionalDiscountAmount, roomLocation, specialProgramCode, totalTaxAmount, prepaidCost, foodAndBeverageCost, roomTaxAmount, adjustmentAmount, phoneCost, restaurantCost, roomServiceCost, miniBarCost, laundryCost, miscellaneousCost, giftShopCost, movieCost, healthClubCost, valetParkingCost, cashDisbursementCost, nonRoomCost, businessCenterCost, loungeBarCost, transportationCost, gratuityAmount, conferenceRoomCost, audioVisualCost, banquestCost, nonRoomTaxAmount, earlyCheckOutCost, internetAccessCost, name, hotelName, checkInDateTime, checkOutDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePaymentRequestTravelInformationLodging {\n");
    sb.append("    checkInDate: ").append(toIndentedString(checkInDate)).append("\n");
    sb.append("    checkOutDate: ").append(toIndentedString(checkOutDate)).append("\n");
    sb.append("    room: ").append(toIndentedString(room)).append("\n");
    sb.append("    smokingPreference: ").append(toIndentedString(smokingPreference)).append("\n");
    sb.append("    numberOfRooms: ").append(toIndentedString(numberOfRooms)).append("\n");
    sb.append("    numberOfGuests: ").append(toIndentedString(numberOfGuests)).append("\n");
    sb.append("    roomBedType: ").append(toIndentedString(roomBedType)).append("\n");
    sb.append("    roomTaxType: ").append(toIndentedString(roomTaxType)).append("\n");
    sb.append("    roomRateType: ").append(toIndentedString(roomRateType)).append("\n");
    sb.append("    guestName: ").append(toIndentedString(guestName)).append("\n");
    sb.append("    customerServicePhoneNumber: ").append(toIndentedString(customerServicePhoneNumber)).append("\n");
    sb.append("    corporateClientCode: ").append(toIndentedString(corporateClientCode)).append("\n");
    sb.append("    additionalDiscountAmount: ").append(toIndentedString(additionalDiscountAmount)).append("\n");
    sb.append("    roomLocation: ").append(toIndentedString(roomLocation)).append("\n");
    sb.append("    specialProgramCode: ").append(toIndentedString(specialProgramCode)).append("\n");
    sb.append("    totalTaxAmount: ").append(toIndentedString(totalTaxAmount)).append("\n");
    sb.append("    prepaidCost: ").append(toIndentedString(prepaidCost)).append("\n");
    sb.append("    foodAndBeverageCost: ").append(toIndentedString(foodAndBeverageCost)).append("\n");
    sb.append("    roomTaxAmount: ").append(toIndentedString(roomTaxAmount)).append("\n");
    sb.append("    adjustmentAmount: ").append(toIndentedString(adjustmentAmount)).append("\n");
    sb.append("    phoneCost: ").append(toIndentedString(phoneCost)).append("\n");
    sb.append("    restaurantCost: ").append(toIndentedString(restaurantCost)).append("\n");
    sb.append("    roomServiceCost: ").append(toIndentedString(roomServiceCost)).append("\n");
    sb.append("    miniBarCost: ").append(toIndentedString(miniBarCost)).append("\n");
    sb.append("    laundryCost: ").append(toIndentedString(laundryCost)).append("\n");
    sb.append("    miscellaneousCost: ").append(toIndentedString(miscellaneousCost)).append("\n");
    sb.append("    giftShopCost: ").append(toIndentedString(giftShopCost)).append("\n");
    sb.append("    movieCost: ").append(toIndentedString(movieCost)).append("\n");
    sb.append("    healthClubCost: ").append(toIndentedString(healthClubCost)).append("\n");
    sb.append("    valetParkingCost: ").append(toIndentedString(valetParkingCost)).append("\n");
    sb.append("    cashDisbursementCost: ").append(toIndentedString(cashDisbursementCost)).append("\n");
    sb.append("    nonRoomCost: ").append(toIndentedString(nonRoomCost)).append("\n");
    sb.append("    businessCenterCost: ").append(toIndentedString(businessCenterCost)).append("\n");
    sb.append("    loungeBarCost: ").append(toIndentedString(loungeBarCost)).append("\n");
    sb.append("    transportationCost: ").append(toIndentedString(transportationCost)).append("\n");
    sb.append("    gratuityAmount: ").append(toIndentedString(gratuityAmount)).append("\n");
    sb.append("    conferenceRoomCost: ").append(toIndentedString(conferenceRoomCost)).append("\n");
    sb.append("    audioVisualCost: ").append(toIndentedString(audioVisualCost)).append("\n");
    sb.append("    banquestCost: ").append(toIndentedString(banquestCost)).append("\n");
    sb.append("    nonRoomTaxAmount: ").append(toIndentedString(nonRoomTaxAmount)).append("\n");
    sb.append("    earlyCheckOutCost: ").append(toIndentedString(earlyCheckOutCost)).append("\n");
    sb.append("    internetAccessCost: ").append(toIndentedString(internetAccessCost)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    hotelName: ").append(toIndentedString(hotelName)).append("\n");
    sb.append("    checkInDateTime: ").append(toIndentedString(checkInDateTime)).append("\n");
    sb.append("    checkOutDateTime: ").append(toIndentedString(checkOutDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

