/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CapturePaymentRequestAggregatorInformation;
import org.openapitools.client.model.CapturePaymentRequestBuyerInformation;
import org.openapitools.client.model.CapturePaymentRequestDeviceInformation;
import org.openapitools.client.model.CreateCreditRequestInstallmentInformation;
import org.openapitools.client.model.CreateCreditRequestProcessingInformation;
import org.openapitools.client.model.CreateCreditRequestRecipientInformation;
import org.openapitools.client.model.CreateCreditRequestSenderInformation;
import org.openapitools.client.model.CreatePaymentRequestClientReferenceInformation;
import org.openapitools.client.model.CreatePaymentRequestMerchantDefinedInformationInner;
import org.openapitools.client.model.CreatePaymentRequestMerchantDefinedSecureInformation;
import org.openapitools.client.model.CreatePaymentRequestPointOfSaleInformation;
import org.openapitools.client.model.CreatePaymentRequestPromotionInformation;
import org.openapitools.client.model.CreatePaymentRequestTravelInformation;
import org.openapitools.client.model.RefundPaymentRequestMerchantInformation;
import org.openapitools.client.model.RefundPaymentRequestOrderInformation;
import org.openapitools.client.model.RefundPaymentRequestPaymentInformation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateCreditRequest
 */
@JsonPropertyOrder({
  CreateCreditRequest.JSON_PROPERTY_CLIENT_REFERENCE_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_PROCESSING_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_PAYMENT_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_ORDER_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_BUYER_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_DEVICE_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_MERCHANT_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_AGGREGATOR_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_POINT_OF_SALE_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_MERCHANT_DEFINED_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_MERCHANT_DEFINED_SECURE_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_INSTALLMENT_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_TRAVEL_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_RECIPIENT_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_SENDER_INFORMATION,
  CreateCreditRequest.JSON_PROPERTY_PROMOTION_INFORMATION
})
@JsonTypeName("createCredit_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T18:32:10.370382+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class CreateCreditRequest {
  public static final String JSON_PROPERTY_CLIENT_REFERENCE_INFORMATION = "clientReferenceInformation";
  private CreatePaymentRequestClientReferenceInformation clientReferenceInformation;

  public static final String JSON_PROPERTY_PROCESSING_INFORMATION = "processingInformation";
  private CreateCreditRequestProcessingInformation processingInformation;

  public static final String JSON_PROPERTY_PAYMENT_INFORMATION = "paymentInformation";
  private RefundPaymentRequestPaymentInformation paymentInformation;

  public static final String JSON_PROPERTY_ORDER_INFORMATION = "orderInformation";
  private RefundPaymentRequestOrderInformation orderInformation;

  public static final String JSON_PROPERTY_BUYER_INFORMATION = "buyerInformation";
  private CapturePaymentRequestBuyerInformation buyerInformation;

  public static final String JSON_PROPERTY_DEVICE_INFORMATION = "deviceInformation";
  private CapturePaymentRequestDeviceInformation deviceInformation;

  public static final String JSON_PROPERTY_MERCHANT_INFORMATION = "merchantInformation";
  private RefundPaymentRequestMerchantInformation merchantInformation;

  public static final String JSON_PROPERTY_AGGREGATOR_INFORMATION = "aggregatorInformation";
  private CapturePaymentRequestAggregatorInformation aggregatorInformation;

  public static final String JSON_PROPERTY_POINT_OF_SALE_INFORMATION = "pointOfSaleInformation";
  private CreatePaymentRequestPointOfSaleInformation pointOfSaleInformation;

  public static final String JSON_PROPERTY_MERCHANT_DEFINED_INFORMATION = "merchantDefinedInformation";
  private List<CreatePaymentRequestMerchantDefinedInformationInner> merchantDefinedInformation = new ArrayList<>();

  public static final String JSON_PROPERTY_MERCHANT_DEFINED_SECURE_INFORMATION = "merchantDefinedSecureInformation";
  private CreatePaymentRequestMerchantDefinedSecureInformation merchantDefinedSecureInformation;

  public static final String JSON_PROPERTY_INSTALLMENT_INFORMATION = "installmentInformation";
  private CreateCreditRequestInstallmentInformation installmentInformation;

  public static final String JSON_PROPERTY_TRAVEL_INFORMATION = "travelInformation";
  private CreatePaymentRequestTravelInformation travelInformation;

  public static final String JSON_PROPERTY_RECIPIENT_INFORMATION = "recipientInformation";
  private CreateCreditRequestRecipientInformation recipientInformation;

  public static final String JSON_PROPERTY_SENDER_INFORMATION = "senderInformation";
  private CreateCreditRequestSenderInformation senderInformation;

  public static final String JSON_PROPERTY_PROMOTION_INFORMATION = "promotionInformation";
  private CreatePaymentRequestPromotionInformation promotionInformation;

  public CreateCreditRequest() {
  }

  public CreateCreditRequest clientReferenceInformation(CreatePaymentRequestClientReferenceInformation clientReferenceInformation) {
    
    this.clientReferenceInformation = clientReferenceInformation;
    return this;
  }

  /**
   * Get clientReferenceInformation
   * @return clientReferenceInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_REFERENCE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreatePaymentRequestClientReferenceInformation getClientReferenceInformation() {
    return clientReferenceInformation;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_REFERENCE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientReferenceInformation(CreatePaymentRequestClientReferenceInformation clientReferenceInformation) {
    this.clientReferenceInformation = clientReferenceInformation;
  }

  public CreateCreditRequest processingInformation(CreateCreditRequestProcessingInformation processingInformation) {
    
    this.processingInformation = processingInformation;
    return this;
  }

  /**
   * Get processingInformation
   * @return processingInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESSING_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreateCreditRequestProcessingInformation getProcessingInformation() {
    return processingInformation;
  }


  @JsonProperty(JSON_PROPERTY_PROCESSING_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessingInformation(CreateCreditRequestProcessingInformation processingInformation) {
    this.processingInformation = processingInformation;
  }

  public CreateCreditRequest paymentInformation(RefundPaymentRequestPaymentInformation paymentInformation) {
    
    this.paymentInformation = paymentInformation;
    return this;
  }

  /**
   * Get paymentInformation
   * @return paymentInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RefundPaymentRequestPaymentInformation getPaymentInformation() {
    return paymentInformation;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentInformation(RefundPaymentRequestPaymentInformation paymentInformation) {
    this.paymentInformation = paymentInformation;
  }

  public CreateCreditRequest orderInformation(RefundPaymentRequestOrderInformation orderInformation) {
    
    this.orderInformation = orderInformation;
    return this;
  }

  /**
   * Get orderInformation
   * @return orderInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RefundPaymentRequestOrderInformation getOrderInformation() {
    return orderInformation;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderInformation(RefundPaymentRequestOrderInformation orderInformation) {
    this.orderInformation = orderInformation;
  }

  public CreateCreditRequest buyerInformation(CapturePaymentRequestBuyerInformation buyerInformation) {
    
    this.buyerInformation = buyerInformation;
    return this;
  }

  /**
   * Get buyerInformation
   * @return buyerInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUYER_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CapturePaymentRequestBuyerInformation getBuyerInformation() {
    return buyerInformation;
  }


  @JsonProperty(JSON_PROPERTY_BUYER_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyerInformation(CapturePaymentRequestBuyerInformation buyerInformation) {
    this.buyerInformation = buyerInformation;
  }

  public CreateCreditRequest deviceInformation(CapturePaymentRequestDeviceInformation deviceInformation) {
    
    this.deviceInformation = deviceInformation;
    return this;
  }

  /**
   * Get deviceInformation
   * @return deviceInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CapturePaymentRequestDeviceInformation getDeviceInformation() {
    return deviceInformation;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceInformation(CapturePaymentRequestDeviceInformation deviceInformation) {
    this.deviceInformation = deviceInformation;
  }

  public CreateCreditRequest merchantInformation(RefundPaymentRequestMerchantInformation merchantInformation) {
    
    this.merchantInformation = merchantInformation;
    return this;
  }

  /**
   * Get merchantInformation
   * @return merchantInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RefundPaymentRequestMerchantInformation getMerchantInformation() {
    return merchantInformation;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantInformation(RefundPaymentRequestMerchantInformation merchantInformation) {
    this.merchantInformation = merchantInformation;
  }

  public CreateCreditRequest aggregatorInformation(CapturePaymentRequestAggregatorInformation aggregatorInformation) {
    
    this.aggregatorInformation = aggregatorInformation;
    return this;
  }

  /**
   * Get aggregatorInformation
   * @return aggregatorInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGGREGATOR_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CapturePaymentRequestAggregatorInformation getAggregatorInformation() {
    return aggregatorInformation;
  }


  @JsonProperty(JSON_PROPERTY_AGGREGATOR_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAggregatorInformation(CapturePaymentRequestAggregatorInformation aggregatorInformation) {
    this.aggregatorInformation = aggregatorInformation;
  }

  public CreateCreditRequest pointOfSaleInformation(CreatePaymentRequestPointOfSaleInformation pointOfSaleInformation) {
    
    this.pointOfSaleInformation = pointOfSaleInformation;
    return this;
  }

  /**
   * Get pointOfSaleInformation
   * @return pointOfSaleInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POINT_OF_SALE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreatePaymentRequestPointOfSaleInformation getPointOfSaleInformation() {
    return pointOfSaleInformation;
  }


  @JsonProperty(JSON_PROPERTY_POINT_OF_SALE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPointOfSaleInformation(CreatePaymentRequestPointOfSaleInformation pointOfSaleInformation) {
    this.pointOfSaleInformation = pointOfSaleInformation;
  }

  public CreateCreditRequest merchantDefinedInformation(List<CreatePaymentRequestMerchantDefinedInformationInner> merchantDefinedInformation) {
    
    this.merchantDefinedInformation = merchantDefinedInformation;
    return this;
  }

  public CreateCreditRequest addMerchantDefinedInformationItem(CreatePaymentRequestMerchantDefinedInformationInner merchantDefinedInformationItem) {
    if (this.merchantDefinedInformation == null) {
      this.merchantDefinedInformation = new ArrayList<>();
    }
    this.merchantDefinedInformation.add(merchantDefinedInformationItem);
    return this;
  }

  /**
   * The object containing the custom data that the merchant defines. 
   * @return merchantDefinedInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_DEFINED_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CreatePaymentRequestMerchantDefinedInformationInner> getMerchantDefinedInformation() {
    return merchantDefinedInformation;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_DEFINED_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantDefinedInformation(List<CreatePaymentRequestMerchantDefinedInformationInner> merchantDefinedInformation) {
    this.merchantDefinedInformation = merchantDefinedInformation;
  }

  public CreateCreditRequest merchantDefinedSecureInformation(CreatePaymentRequestMerchantDefinedSecureInformation merchantDefinedSecureInformation) {
    
    this.merchantDefinedSecureInformation = merchantDefinedSecureInformation;
    return this;
  }

  /**
   * Get merchantDefinedSecureInformation
   * @return merchantDefinedSecureInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_DEFINED_SECURE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreatePaymentRequestMerchantDefinedSecureInformation getMerchantDefinedSecureInformation() {
    return merchantDefinedSecureInformation;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_DEFINED_SECURE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantDefinedSecureInformation(CreatePaymentRequestMerchantDefinedSecureInformation merchantDefinedSecureInformation) {
    this.merchantDefinedSecureInformation = merchantDefinedSecureInformation;
  }

  public CreateCreditRequest installmentInformation(CreateCreditRequestInstallmentInformation installmentInformation) {
    
    this.installmentInformation = installmentInformation;
    return this;
  }

  /**
   * Get installmentInformation
   * @return installmentInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTALLMENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreateCreditRequestInstallmentInformation getInstallmentInformation() {
    return installmentInformation;
  }


  @JsonProperty(JSON_PROPERTY_INSTALLMENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstallmentInformation(CreateCreditRequestInstallmentInformation installmentInformation) {
    this.installmentInformation = installmentInformation;
  }

  public CreateCreditRequest travelInformation(CreatePaymentRequestTravelInformation travelInformation) {
    
    this.travelInformation = travelInformation;
    return this;
  }

  /**
   * Get travelInformation
   * @return travelInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAVEL_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreatePaymentRequestTravelInformation getTravelInformation() {
    return travelInformation;
  }


  @JsonProperty(JSON_PROPERTY_TRAVEL_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTravelInformation(CreatePaymentRequestTravelInformation travelInformation) {
    this.travelInformation = travelInformation;
  }

  public CreateCreditRequest recipientInformation(CreateCreditRequestRecipientInformation recipientInformation) {
    
    this.recipientInformation = recipientInformation;
    return this;
  }

  /**
   * Get recipientInformation
   * @return recipientInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECIPIENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreateCreditRequestRecipientInformation getRecipientInformation() {
    return recipientInformation;
  }


  @JsonProperty(JSON_PROPERTY_RECIPIENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecipientInformation(CreateCreditRequestRecipientInformation recipientInformation) {
    this.recipientInformation = recipientInformation;
  }

  public CreateCreditRequest senderInformation(CreateCreditRequestSenderInformation senderInformation) {
    
    this.senderInformation = senderInformation;
    return this;
  }

  /**
   * Get senderInformation
   * @return senderInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENDER_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreateCreditRequestSenderInformation getSenderInformation() {
    return senderInformation;
  }


  @JsonProperty(JSON_PROPERTY_SENDER_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSenderInformation(CreateCreditRequestSenderInformation senderInformation) {
    this.senderInformation = senderInformation;
  }

  public CreateCreditRequest promotionInformation(CreatePaymentRequestPromotionInformation promotionInformation) {
    
    this.promotionInformation = promotionInformation;
    return this;
  }

  /**
   * Get promotionInformation
   * @return promotionInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROMOTION_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreatePaymentRequestPromotionInformation getPromotionInformation() {
    return promotionInformation;
  }


  @JsonProperty(JSON_PROPERTY_PROMOTION_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromotionInformation(CreatePaymentRequestPromotionInformation promotionInformation) {
    this.promotionInformation = promotionInformation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCreditRequest createCreditRequest = (CreateCreditRequest) o;
    return Objects.equals(this.clientReferenceInformation, createCreditRequest.clientReferenceInformation) &&
        Objects.equals(this.processingInformation, createCreditRequest.processingInformation) &&
        Objects.equals(this.paymentInformation, createCreditRequest.paymentInformation) &&
        Objects.equals(this.orderInformation, createCreditRequest.orderInformation) &&
        Objects.equals(this.buyerInformation, createCreditRequest.buyerInformation) &&
        Objects.equals(this.deviceInformation, createCreditRequest.deviceInformation) &&
        Objects.equals(this.merchantInformation, createCreditRequest.merchantInformation) &&
        Objects.equals(this.aggregatorInformation, createCreditRequest.aggregatorInformation) &&
        Objects.equals(this.pointOfSaleInformation, createCreditRequest.pointOfSaleInformation) &&
        Objects.equals(this.merchantDefinedInformation, createCreditRequest.merchantDefinedInformation) &&
        Objects.equals(this.merchantDefinedSecureInformation, createCreditRequest.merchantDefinedSecureInformation) &&
        Objects.equals(this.installmentInformation, createCreditRequest.installmentInformation) &&
        Objects.equals(this.travelInformation, createCreditRequest.travelInformation) &&
        Objects.equals(this.recipientInformation, createCreditRequest.recipientInformation) &&
        Objects.equals(this.senderInformation, createCreditRequest.senderInformation) &&
        Objects.equals(this.promotionInformation, createCreditRequest.promotionInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientReferenceInformation, processingInformation, paymentInformation, orderInformation, buyerInformation, deviceInformation, merchantInformation, aggregatorInformation, pointOfSaleInformation, merchantDefinedInformation, merchantDefinedSecureInformation, installmentInformation, travelInformation, recipientInformation, senderInformation, promotionInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCreditRequest {\n");
    sb.append("    clientReferenceInformation: ").append(toIndentedString(clientReferenceInformation)).append("\n");
    sb.append("    processingInformation: ").append(toIndentedString(processingInformation)).append("\n");
    sb.append("    paymentInformation: ").append(toIndentedString(paymentInformation)).append("\n");
    sb.append("    orderInformation: ").append(toIndentedString(orderInformation)).append("\n");
    sb.append("    buyerInformation: ").append(toIndentedString(buyerInformation)).append("\n");
    sb.append("    deviceInformation: ").append(toIndentedString(deviceInformation)).append("\n");
    sb.append("    merchantInformation: ").append(toIndentedString(merchantInformation)).append("\n");
    sb.append("    aggregatorInformation: ").append(toIndentedString(aggregatorInformation)).append("\n");
    sb.append("    pointOfSaleInformation: ").append(toIndentedString(pointOfSaleInformation)).append("\n");
    sb.append("    merchantDefinedInformation: ").append(toIndentedString(merchantDefinedInformation)).append("\n");
    sb.append("    merchantDefinedSecureInformation: ").append(toIndentedString(merchantDefinedSecureInformation)).append("\n");
    sb.append("    installmentInformation: ").append(toIndentedString(installmentInformation)).append("\n");
    sb.append("    travelInformation: ").append(toIndentedString(travelInformation)).append("\n");
    sb.append("    recipientInformation: ").append(toIndentedString(recipientInformation)).append("\n");
    sb.append("    senderInformation: ").append(toIndentedString(senderInformation)).append("\n");
    sb.append("    promotionInformation: ").append(toIndentedString(promotionInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

