/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * List of the line items from the order, which are included in an invoice.
 */
@JsonPropertyOrder({
  CreateInvoiceRequestOrderInformationLineItemsInner.JSON_PROPERTY_PRODUCT_SKU,
  CreateInvoiceRequestOrderInformationLineItemsInner.JSON_PROPERTY_PRODUCT_NAME,
  CreateInvoiceRequestOrderInformationLineItemsInner.JSON_PROPERTY_QUANTITY,
  CreateInvoiceRequestOrderInformationLineItemsInner.JSON_PROPERTY_UNIT_PRICE,
  CreateInvoiceRequestOrderInformationLineItemsInner.JSON_PROPERTY_DISCOUNT_AMOUNT,
  CreateInvoiceRequestOrderInformationLineItemsInner.JSON_PROPERTY_DISCOUNT_RATE,
  CreateInvoiceRequestOrderInformationLineItemsInner.JSON_PROPERTY_TAX_AMOUNT,
  CreateInvoiceRequestOrderInformationLineItemsInner.JSON_PROPERTY_TAX_RATE,
  CreateInvoiceRequestOrderInformationLineItemsInner.JSON_PROPERTY_TOTAL_AMOUNT
})
@JsonTypeName("createInvoice_request_orderInformation_lineItems_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T18:32:10.370382+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class CreateInvoiceRequestOrderInformationLineItemsInner {
  public static final String JSON_PROPERTY_PRODUCT_SKU = "productSku";
  private String productSku;

  public static final String JSON_PROPERTY_PRODUCT_NAME = "productName";
  private String productName;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Integer quantity;

  public static final String JSON_PROPERTY_UNIT_PRICE = "unitPrice";
  private String unitPrice;

  public static final String JSON_PROPERTY_DISCOUNT_AMOUNT = "discountAmount";
  private String discountAmount;

  public static final String JSON_PROPERTY_DISCOUNT_RATE = "discountRate";
  private String discountRate;

  public static final String JSON_PROPERTY_TAX_AMOUNT = "taxAmount";
  private String taxAmount;

  public static final String JSON_PROPERTY_TAX_RATE = "taxRate";
  private String taxRate;

  public static final String JSON_PROPERTY_TOTAL_AMOUNT = "totalAmount";
  private String totalAmount;

  public CreateInvoiceRequestOrderInformationLineItemsInner() {
  }

  public CreateInvoiceRequestOrderInformationLineItemsInner productSku(String productSku) {
    
    this.productSku = productSku;
    return this;
  }

  /**
   * Product identifier code. Also known as the Stock Keeping Unit (SKU) code for the product.  For an authorization or capture transaction (&#x60;processingOptions.capture&#x60; is set to &#x60;true&#x60; or &#x60;false&#x60;), this field is required when &#x60;orderInformation.lineItems[].productCode&#x60; is not set to **default** or one of the other values that are related to shipping and/or handling.  #### Tax Calculation Optional field for U.S. and Canadian taxes. Not applicable to international and value added taxes. For an authorization or capture transaction (&#x60;processingOptions.capture&#x60; is set to &#x60;true&#x60; or &#x60;false&#x60;), this field is required when &#x60;orderInformation.lineItems[].productCode&#x60; is not &#x60;default&#x60; or one of the values related to shipping and/or handling. 
   * @return productSku
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRODUCT_SKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductSku() {
    return productSku;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_SKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductSku(String productSku) {
    this.productSku = productSku;
  }

  public CreateInvoiceRequestOrderInformationLineItemsInner productName(String productName) {
    
    this.productName = productName;
    return this;
  }

  /**
   * For an authorization or capture transaction (&#x60;processingOptions.capture&#x60; is &#x60;true&#x60; or &#x60;false&#x60;), this field is required when &#x60;orderInformation.lineItems[].productCode&#x60; is not &#x60;default&#x60; or one of the other values that are related to shipping and/or handling.  #### Tax Calculation Optional field for U.S., Canadian, international tax, and value added taxes. 
   * @return productName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRODUCT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductName() {
    return productName;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductName(String productName) {
    this.productName = productName;
  }

  public CreateInvoiceRequestOrderInformationLineItemsInner quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

  /**
   * Number of units for this order. Must be a non-negative integer.  The default is &#x60;1&#x60;. For an authorization or capture transaction (&#x60;processingOptions.capture&#x60; is set to &#x60;true&#x60; or &#x60;false&#x60;), this field is required when &#x60;orderInformation.lineItems[].productCode&#x60; is not &#x60;default&#x60; or one of the other values related to shipping and/or handling.  #### Tax Calculation Optional field for U.S., Canadian, international tax, and value added taxes. 
   * minimum: 1
   * maximum: 999999999
   * @return quantity
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public CreateInvoiceRequestOrderInformationLineItemsInner unitPrice(String unitPrice) {
    
    this.unitPrice = unitPrice;
    return this;
  }

  /**
   * Per-item price of the product. This value for this field cannot be negative.  You must include either this field or the request-level field &#x60;orderInformation.amountDetails.totalAmount&#x60; in your request.  You can include a decimal point (.), but you cannot include any other special characters. The value is truncated to the correct number of decimal places.  #### DCC with a Third-Party Provider Set this field to the converted amount that was returned by the DCC provider. You must include either the 1st line item in the order and this field, or the request-level field &#x60;orderInformation.amountDetails.totalAmount&#x60; in your request.  #### Tax Calculation Required field for U.S., Canadian, international and value added taxes.  #### Zero Amount Authorizations If your processor supports zero amount authorizations, you can set this field to 0 for the authorization to check if the card is lost or stolen.  #### Maximum Field Lengths For GPN and JCN Gateway: Decimal (10) All other processors: Decimal (15) 
   * @return unitPrice
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIT_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnitPrice() {
    return unitPrice;
  }


  @JsonProperty(JSON_PROPERTY_UNIT_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnitPrice(String unitPrice) {
    this.unitPrice = unitPrice;
  }

  public CreateInvoiceRequestOrderInformationLineItemsInner discountAmount(String discountAmount) {
    
    this.discountAmount = discountAmount;
    return this;
  }

  /**
   * Discount applied to the item.
   * @return discountAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCOUNT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDiscountAmount() {
    return discountAmount;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountAmount(String discountAmount) {
    this.discountAmount = discountAmount;
  }

  public CreateInvoiceRequestOrderInformationLineItemsInner discountRate(String discountRate) {
    
    this.discountRate = discountRate;
    return this;
  }

  /**
   * Rate the item is discounted. Maximum of 2 decimal places.  Example 5.25 (&#x3D;5.25%) 
   * @return discountRate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCOUNT_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDiscountRate() {
    return discountRate;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountRate(String discountRate) {
    this.discountRate = discountRate;
  }

  public CreateInvoiceRequestOrderInformationLineItemsInner taxAmount(String taxAmount) {
    
    this.taxAmount = taxAmount;
    return this;
  }

  /**
   * Total tax to apply to the product. This value cannot be negative. The tax amount and the offer amount must be in the same currency. The tax amount field is additive.  The following example uses a two-exponent currency such as USD:   1. You include each line item in your request.  ..- 1st line item has amount&#x3D;10.00, quantity&#x3D;1, and taxAmount&#x3D;0.80  ..- 2nd line item has amount&#x3D;20.00, quantity&#x3D;1, and taxAmount&#x3D;1.60  2. The total amount authorized will be 32.40, not 30.00 with 2.40 of tax included.  Optional field.  #### Airlines processing Tax portion of the order amount. This value cannot exceed 99999999999999 (fourteen 9s). Format: English characters only. Optional request field for a line item.  #### Tax Calculation Optional field for U.S., Canadian, international tax, and value added taxes.  Note if you send this field in your tax request, the value in the field will override the tax engine 
   * @return taxAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaxAmount() {
    return taxAmount;
  }


  @JsonProperty(JSON_PROPERTY_TAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxAmount(String taxAmount) {
    this.taxAmount = taxAmount;
  }

  public CreateInvoiceRequestOrderInformationLineItemsInner taxRate(String taxRate) {
    
    this.taxRate = taxRate;
    return this;
  }

  /**
   * Tax rate applied to the item.  **Visa**: Valid range is 0.01 to 0.99 (1% to 99%, with only whole percentage values accepted; values with additional decimal places will be truncated).  **Mastercard**: Valid range is 0.00001 to 0.99999 (0.001% to 99.999%). 
   * @return taxRate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaxRate() {
    return taxRate;
  }


  @JsonProperty(JSON_PROPERTY_TAX_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxRate(String taxRate) {
    this.taxRate = taxRate;
  }

  public CreateInvoiceRequestOrderInformationLineItemsInner totalAmount(String totalAmount) {
    
    this.totalAmount = totalAmount;
    return this;
  }

  /**
   * Total amount for the item. Normally calculated as the unit price times quantity.  When &#x60;orderInformation.lineItems[].productCode&#x60; is \&quot;gift_card\&quot;, this is the purchase amount total for prepaid gift cards in major units.  Example: 123.45 USD &#x3D; 123 
   * @return totalAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTotalAmount() {
    return totalAmount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalAmount(String totalAmount) {
    this.totalAmount = totalAmount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateInvoiceRequestOrderInformationLineItemsInner createInvoiceRequestOrderInformationLineItemsInner = (CreateInvoiceRequestOrderInformationLineItemsInner) o;
    return Objects.equals(this.productSku, createInvoiceRequestOrderInformationLineItemsInner.productSku) &&
        Objects.equals(this.productName, createInvoiceRequestOrderInformationLineItemsInner.productName) &&
        Objects.equals(this.quantity, createInvoiceRequestOrderInformationLineItemsInner.quantity) &&
        Objects.equals(this.unitPrice, createInvoiceRequestOrderInformationLineItemsInner.unitPrice) &&
        Objects.equals(this.discountAmount, createInvoiceRequestOrderInformationLineItemsInner.discountAmount) &&
        Objects.equals(this.discountRate, createInvoiceRequestOrderInformationLineItemsInner.discountRate) &&
        Objects.equals(this.taxAmount, createInvoiceRequestOrderInformationLineItemsInner.taxAmount) &&
        Objects.equals(this.taxRate, createInvoiceRequestOrderInformationLineItemsInner.taxRate) &&
        Objects.equals(this.totalAmount, createInvoiceRequestOrderInformationLineItemsInner.totalAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productSku, productName, quantity, unitPrice, discountAmount, discountRate, taxAmount, taxRate, totalAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateInvoiceRequestOrderInformationLineItemsInner {\n");
    sb.append("    productSku: ").append(toIndentedString(productSku)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    discountRate: ").append(toIndentedString(discountRate)).append("\n");
    sb.append("    taxAmount: ").append(toIndentedString(taxAmount)).append("\n");
    sb.append("    taxRate: ").append(toIndentedString(taxRate)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

