/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreatePaymentRequestAgreementInformation
 */
@JsonPropertyOrder({
  CreatePaymentRequestAgreementInformation.JSON_PROPERTY_AGREEMENT_ID
})
@JsonTypeName("createPayment_request_agreementInformation")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class CreatePaymentRequestAgreementInformation {
  public static final String JSON_PROPERTY_AGREEMENT_ID = "agreementId";
  private String agreementId;

  public CreatePaymentRequestAgreementInformation() {
  }

  public CreatePaymentRequestAgreementInformation agreementId(String agreementId) {
    
    this.agreementId = agreementId;
    return this;
  }

  /**
   * Identifier for the mandate being signed for. This mandate id is required for all the subsequent transactions.  
   * @return agreementId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAgreementId() {
    return agreementId;
  }


  @JsonProperty(JSON_PROPERTY_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgreementId(String agreementId) {
    this.agreementId = agreementId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePaymentRequestAgreementInformation createPaymentRequestAgreementInformation = (CreatePaymentRequestAgreementInformation) o;
    return Objects.equals(this.agreementId, createPaymentRequestAgreementInformation.agreementId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agreementId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePaymentRequestAgreementInformation {\n");
    sb.append("    agreementId: ").append(toIndentedString(agreementId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

