/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import org.openapitools.client.model.SAConfig;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PaymentsProductsSecureAcceptanceConfigurationInformation
 */
@JsonPropertyOrder({
  PaymentsProductsSecureAcceptanceConfigurationInformation.JSON_PROPERTY_TEMPLATE_ID,
  PaymentsProductsSecureAcceptanceConfigurationInformation.JSON_PROPERTY_CONFIGURATIONS
})
@JsonTypeName("paymentsProducts_secureAcceptance_configurationInformation")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class PaymentsProductsSecureAcceptanceConfigurationInformation {
  public static final String JSON_PROPERTY_TEMPLATE_ID = "templateId";
  private UUID templateId;

  public static final String JSON_PROPERTY_CONFIGURATIONS = "configurations";
  private SAConfig configurations;

  public PaymentsProductsSecureAcceptanceConfigurationInformation() {
  }

  public PaymentsProductsSecureAcceptanceConfigurationInformation templateId(UUID templateId) {
    
    this.templateId = templateId;
    return this;
  }

  /**
   * Get templateId
   * @return templateId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEMPLATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getTemplateId() {
    return templateId;
  }


  @JsonProperty(JSON_PROPERTY_TEMPLATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplateId(UUID templateId) {
    this.templateId = templateId;
  }

  public PaymentsProductsSecureAcceptanceConfigurationInformation configurations(SAConfig configurations) {
    
    this.configurations = configurations;
    return this;
  }

  /**
   * Get configurations
   * @return configurations
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIGURATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SAConfig getConfigurations() {
    return configurations;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGURATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigurations(SAConfig configurations) {
    this.configurations = configurations;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentsProductsSecureAcceptanceConfigurationInformation paymentsProductsSecureAcceptanceConfigurationInformation = (PaymentsProductsSecureAcceptanceConfigurationInformation) o;
    return Objects.equals(this.templateId, paymentsProductsSecureAcceptanceConfigurationInformation.templateId) &&
        Objects.equals(this.configurations, paymentsProductsSecureAcceptanceConfigurationInformation.configurations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateId, configurations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentsProductsSecureAcceptanceConfigurationInformation {\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    configurations: ").append(toIndentedString(configurations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

