/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PaymentInstrumentListEmbeddedPaymentInstrumentsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Payment Instrument Resources. 
 */
@JsonPropertyOrder({
  PaymentInstrumentListEmbedded.JSON_PROPERTY_PAYMENT_INSTRUMENTS
})
@JsonTypeName("PaymentInstrumentList__embedded")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class PaymentInstrumentListEmbedded {
  public static final String JSON_PROPERTY_PAYMENT_INSTRUMENTS = "paymentInstruments";
  private List<PaymentInstrumentListEmbeddedPaymentInstrumentsInner> paymentInstruments = new ArrayList<>();

  public PaymentInstrumentListEmbedded() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public PaymentInstrumentListEmbedded(
    @JsonProperty(JSON_PROPERTY_PAYMENT_INSTRUMENTS) List<PaymentInstrumentListEmbeddedPaymentInstrumentsInner> paymentInstruments
  ) {
    this();
    this.paymentInstruments = paymentInstruments;
  }

  /**
   * Get paymentInstruments
   * @return paymentInstruments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_INSTRUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PaymentInstrumentListEmbeddedPaymentInstrumentsInner> getPaymentInstruments() {
    return paymentInstruments;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentInstrumentListEmbedded paymentInstrumentListEmbedded = (PaymentInstrumentListEmbedded) o;
    return Objects.equals(this.paymentInstruments, paymentInstrumentListEmbedded.paymentInstruments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentInstruments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentInstrumentListEmbedded {\n");
    sb.append("    paymentInstruments: ").append(toIndentedString(paymentInstruments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

