/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation
 */
@JsonPropertyOrder({
  PostRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation.JSON_PROPERTY_TENANT_ID
})
@JsonTypeName("postRegistration_request_integrationInformation_tenantConfigurations_inner_tenantInformation")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class PostRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation {
  public static final String JSON_PROPERTY_TENANT_ID = "tenantId";
  private String tenantId;

  public PostRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation() {
  }

  public PostRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation tenantId(String tenantId) {
    
    this.tenantId = tenantId;
    return this;
  }

  /**
   * The TenantId is an external Solution Identifier given by Tech Partners like SAP.
   * @return tenantId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantId() {
    return tenantId;
  }


  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation postRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation = (PostRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation) o;
    return Objects.equals(this.tenantId, postRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation.tenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostRegistrationRequestIntegrationInformationTenantConfigurationsInnerTenantInformation {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

