/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.PtsV2PaymentsPost201ResponseRiskInformationInfoCodes;
import org.openapitools.client.model.PtsV2PaymentsPost201ResponseRiskInformationIpAddress;
import org.openapitools.client.model.PtsV2PaymentsPost201ResponseRiskInformationProcessorResults;
import org.openapitools.client.model.PtsV2PaymentsPost201ResponseRiskInformationProfile;
import org.openapitools.client.model.PtsV2PaymentsPost201ResponseRiskInformationRulesInner;
import org.openapitools.client.model.PtsV2PaymentsPost201ResponseRiskInformationScore;
import org.openapitools.client.model.PtsV2PaymentsPost201ResponseRiskInformationTravel;
import org.openapitools.client.model.PtsV2PaymentsPost201ResponseRiskInformationVelocity;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Contains the result of risk assessment.
 */
@JsonPropertyOrder({
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_PROFILE,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_RULES,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_INFO_CODES,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_VELOCITY,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_CASE_PRIORITY,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_LOCAL_TIME,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_SCORE,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_IP_ADDRESS,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_PROVIDERS,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_TRAVEL,
  PtsV2PaymentsPost201ResponseRiskInformation.JSON_PROPERTY_PROCESSOR_RESULTS
})
@JsonTypeName("ptsV2PaymentsPost201Response_riskInformation")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class PtsV2PaymentsPost201ResponseRiskInformation {
  public static final String JSON_PROPERTY_PROFILE = "profile";
  private PtsV2PaymentsPost201ResponseRiskInformationProfile profile;

  public static final String JSON_PROPERTY_RULES = "rules";
  private List<PtsV2PaymentsPost201ResponseRiskInformationRulesInner> rules = new ArrayList<>();

  public static final String JSON_PROPERTY_INFO_CODES = "infoCodes";
  private PtsV2PaymentsPost201ResponseRiskInformationInfoCodes infoCodes;

  public static final String JSON_PROPERTY_VELOCITY = "velocity";
  private PtsV2PaymentsPost201ResponseRiskInformationVelocity velocity;

  public static final String JSON_PROPERTY_CASE_PRIORITY = "casePriority";
  private Integer casePriority;

  public static final String JSON_PROPERTY_LOCAL_TIME = "localTime";
  private String _localTime;

  public static final String JSON_PROPERTY_SCORE = "score";
  private PtsV2PaymentsPost201ResponseRiskInformationScore score;

  public static final String JSON_PROPERTY_IP_ADDRESS = "ipAddress";
  private PtsV2PaymentsPost201ResponseRiskInformationIpAddress ipAddress;

  public static final String JSON_PROPERTY_PROVIDERS = "providers";
  private Map<String, Map<String, String>> providers = new HashMap<>();

  public static final String JSON_PROPERTY_TRAVEL = "travel";
  private PtsV2PaymentsPost201ResponseRiskInformationTravel travel;

  public static final String JSON_PROPERTY_PROCESSOR_RESULTS = "processorResults";
  private PtsV2PaymentsPost201ResponseRiskInformationProcessorResults processorResults;

  public PtsV2PaymentsPost201ResponseRiskInformation() {
  }

  public PtsV2PaymentsPost201ResponseRiskInformation profile(PtsV2PaymentsPost201ResponseRiskInformationProfile profile) {
    
    this.profile = profile;
    return this;
  }

  /**
   * Get profile
   * @return profile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PtsV2PaymentsPost201ResponseRiskInformationProfile getProfile() {
    return profile;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfile(PtsV2PaymentsPost201ResponseRiskInformationProfile profile) {
    this.profile = profile;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation rules(List<PtsV2PaymentsPost201ResponseRiskInformationRulesInner> rules) {
    
    this.rules = rules;
    return this;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation addRulesItem(PtsV2PaymentsPost201ResponseRiskInformationRulesInner rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

  /**
   * Get rules
   * @return rules
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PtsV2PaymentsPost201ResponseRiskInformationRulesInner> getRules() {
    return rules;
  }


  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRules(List<PtsV2PaymentsPost201ResponseRiskInformationRulesInner> rules) {
    this.rules = rules;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation infoCodes(PtsV2PaymentsPost201ResponseRiskInformationInfoCodes infoCodes) {
    
    this.infoCodes = infoCodes;
    return this;
  }

  /**
   * Get infoCodes
   * @return infoCodes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INFO_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PtsV2PaymentsPost201ResponseRiskInformationInfoCodes getInfoCodes() {
    return infoCodes;
  }


  @JsonProperty(JSON_PROPERTY_INFO_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInfoCodes(PtsV2PaymentsPost201ResponseRiskInformationInfoCodes infoCodes) {
    this.infoCodes = infoCodes;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation velocity(PtsV2PaymentsPost201ResponseRiskInformationVelocity velocity) {
    
    this.velocity = velocity;
    return this;
  }

  /**
   * Get velocity
   * @return velocity
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VELOCITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PtsV2PaymentsPost201ResponseRiskInformationVelocity getVelocity() {
    return velocity;
  }


  @JsonProperty(JSON_PROPERTY_VELOCITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVelocity(PtsV2PaymentsPost201ResponseRiskInformationVelocity velocity) {
    this.velocity = velocity;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation casePriority(Integer casePriority) {
    
    this.casePriority = casePriority;
    return this;
  }

  /**
   * You receive this field only if you subscribe to the Enhanced Case Management service. The priority level ranges from 1 (highest) to 5 (lowest); the default value is 3. If you do not assign a priority to your rules or to your profiles, the default value is given to the order.  For all possible values, see the &#x60;decision_case_priority&#x60; field description in the _Decision Manager Using the SCMP API Developer Guide_ on the [CyberSource Business Center.](https://ebc2.cybersource.com/ebc2/) Click **Decision Manager** &gt; **Documentation** &gt; **Guides** &gt; _Decision Manager Using the SCMP API Developer Guide_ (PDF link). 
   * @return casePriority
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CASE_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCasePriority() {
    return casePriority;
  }


  @JsonProperty(JSON_PROPERTY_CASE_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCasePriority(Integer casePriority) {
    this.casePriority = casePriority;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation _localTime(String _localTime) {
    
    this._localTime = _localTime;
    return this;
  }

  /**
   * The customer&#39;s local time (&#x60;hh:mm:ss&#x60;), which is calculated from the transaction request time and the customer&#39;s billing address.  For details, see the &#x60;score_time_local&#x60; field description in the _Decision Manager Using the SCMP API Developer Guide_ on the [CyberSource Business Center.](https://ebc2.cybersource.com/ebc2/) 
   * @return _localTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCAL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocalTime() {
    return _localTime;
  }


  @JsonProperty(JSON_PROPERTY_LOCAL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalTime(String _localTime) {
    this._localTime = _localTime;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation score(PtsV2PaymentsPost201ResponseRiskInformationScore score) {
    
    this.score = score;
    return this;
  }

  /**
   * Get score
   * @return score
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PtsV2PaymentsPost201ResponseRiskInformationScore getScore() {
    return score;
  }


  @JsonProperty(JSON_PROPERTY_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScore(PtsV2PaymentsPost201ResponseRiskInformationScore score) {
    this.score = score;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation ipAddress(PtsV2PaymentsPost201ResponseRiskInformationIpAddress ipAddress) {
    
    this.ipAddress = ipAddress;
    return this;
  }

  /**
   * Get ipAddress
   * @return ipAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PtsV2PaymentsPost201ResponseRiskInformationIpAddress getIpAddress() {
    return ipAddress;
  }


  @JsonProperty(JSON_PROPERTY_IP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpAddress(PtsV2PaymentsPost201ResponseRiskInformationIpAddress ipAddress) {
    this.ipAddress = ipAddress;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation providers(Map<String, Map<String, String>> providers) {
    
    this.providers = providers;
    return this;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation putProvidersItem(String key, Map<String, String> providersItem) {
    if (this.providers == null) {
      this.providers = new HashMap<>();
    }
    this.providers.put(key, providersItem);
    return this;
  }

  /**
   * Name of the 3rd party provider, for example, Emailage. For all possible values, see the &#x60;decision_provider_#_name&#x60; field description in the _Decision Manager Using the SCMP API Developer Guide_ on the [CyberSource Business Center.](https://ebc2.cybersource.com/ebc2/) Click **Decision Manager** &gt; **Documentation** &gt; **Guides** &gt; _Decision Manager Using the SCMP API Developer Guide_ (PDF link).
   * @return providers
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Map<String, String>> getProviders() {
    return providers;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviders(Map<String, Map<String, String>> providers) {
    this.providers = providers;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation travel(PtsV2PaymentsPost201ResponseRiskInformationTravel travel) {
    
    this.travel = travel;
    return this;
  }

  /**
   * Get travel
   * @return travel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRAVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PtsV2PaymentsPost201ResponseRiskInformationTravel getTravel() {
    return travel;
  }


  @JsonProperty(JSON_PROPERTY_TRAVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTravel(PtsV2PaymentsPost201ResponseRiskInformationTravel travel) {
    this.travel = travel;
  }

  public PtsV2PaymentsPost201ResponseRiskInformation processorResults(PtsV2PaymentsPost201ResponseRiskInformationProcessorResults processorResults) {
    
    this.processorResults = processorResults;
    return this;
  }

  /**
   * Get processorResults
   * @return processorResults
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCESSOR_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PtsV2PaymentsPost201ResponseRiskInformationProcessorResults getProcessorResults() {
    return processorResults;
  }


  @JsonProperty(JSON_PROPERTY_PROCESSOR_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessorResults(PtsV2PaymentsPost201ResponseRiskInformationProcessorResults processorResults) {
    this.processorResults = processorResults;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PtsV2PaymentsPost201ResponseRiskInformation ptsV2PaymentsPost201ResponseRiskInformation = (PtsV2PaymentsPost201ResponseRiskInformation) o;
    return Objects.equals(this.profile, ptsV2PaymentsPost201ResponseRiskInformation.profile) &&
        Objects.equals(this.rules, ptsV2PaymentsPost201ResponseRiskInformation.rules) &&
        Objects.equals(this.infoCodes, ptsV2PaymentsPost201ResponseRiskInformation.infoCodes) &&
        Objects.equals(this.velocity, ptsV2PaymentsPost201ResponseRiskInformation.velocity) &&
        Objects.equals(this.casePriority, ptsV2PaymentsPost201ResponseRiskInformation.casePriority) &&
        Objects.equals(this._localTime, ptsV2PaymentsPost201ResponseRiskInformation._localTime) &&
        Objects.equals(this.score, ptsV2PaymentsPost201ResponseRiskInformation.score) &&
        Objects.equals(this.ipAddress, ptsV2PaymentsPost201ResponseRiskInformation.ipAddress) &&
        Objects.equals(this.providers, ptsV2PaymentsPost201ResponseRiskInformation.providers) &&
        Objects.equals(this.travel, ptsV2PaymentsPost201ResponseRiskInformation.travel) &&
        Objects.equals(this.processorResults, ptsV2PaymentsPost201ResponseRiskInformation.processorResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profile, rules, infoCodes, velocity, casePriority, _localTime, score, ipAddress, providers, travel, processorResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtsV2PaymentsPost201ResponseRiskInformation {\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    infoCodes: ").append(toIndentedString(infoCodes)).append("\n");
    sb.append("    velocity: ").append(toIndentedString(velocity)).append("\n");
    sb.append("    casePriority: ").append(toIndentedString(casePriority)).append("\n");
    sb.append("    _localTime: ").append(toIndentedString(_localTime)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    providers: ").append(toIndentedString(providers)).append("\n");
    sb.append("    travel: ").append(toIndentedString(travel)).append("\n");
    sb.append("    processorResults: ").append(toIndentedString(processorResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

