/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PtsV2PaymentsPost201ResponseRiskInformationProfile
 */
@JsonPropertyOrder({
  PtsV2PaymentsPost201ResponseRiskInformationProfile.JSON_PROPERTY_NAME,
  PtsV2PaymentsPost201ResponseRiskInformationProfile.JSON_PROPERTY_DESINATION_QUEUE,
  PtsV2PaymentsPost201ResponseRiskInformationProfile.JSON_PROPERTY_SELECTOR_RULE
})
@JsonTypeName("ptsV2PaymentsPost201Response_riskInformation_profile")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T18:32:10.370382+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class PtsV2PaymentsPost201ResponseRiskInformationProfile {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESINATION_QUEUE = "desinationQueue";
  private String desinationQueue;

  public static final String JSON_PROPERTY_SELECTOR_RULE = "selectorRule";
  private String selectorRule;

  public PtsV2PaymentsPost201ResponseRiskInformationProfile() {
  }

  public PtsV2PaymentsPost201ResponseRiskInformationProfile name(String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Name of the active profile chosen by the profile selector. If no profile selector exists, the default active profile is chosen.  **Note** By default, your default profile is the active profile, or the Profile Selector chooses the active profile. Use this field only if you want to specify the name of a different profile. The passed-in profile will then become the active profile. 
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  public PtsV2PaymentsPost201ResponseRiskInformationProfile desinationQueue(String desinationQueue) {
    
    this.desinationQueue = desinationQueue;
    return this;
  }

  /**
   * Name of the queue where orders that are not automatically accepted are sent. 
   * @return desinationQueue
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESINATION_QUEUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDesinationQueue() {
    return desinationQueue;
  }


  @JsonProperty(JSON_PROPERTY_DESINATION_QUEUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDesinationQueue(String desinationQueue) {
    this.desinationQueue = desinationQueue;
  }

  public PtsV2PaymentsPost201ResponseRiskInformationProfile selectorRule(String selectorRule) {
    
    this.selectorRule = selectorRule;
    return this;
  }

  /**
   * Name of the profile selector rule that chooses the profile to use for the transaction. If no profile selector exists, the value is Default Active Profile. 
   * @return selectorRule
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELECTOR_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelectorRule() {
    return selectorRule;
  }


  @JsonProperty(JSON_PROPERTY_SELECTOR_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelectorRule(String selectorRule) {
    this.selectorRule = selectorRule;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PtsV2PaymentsPost201ResponseRiskInformationProfile ptsV2PaymentsPost201ResponseRiskInformationProfile = (PtsV2PaymentsPost201ResponseRiskInformationProfile) o;
    return Objects.equals(this.name, ptsV2PaymentsPost201ResponseRiskInformationProfile.name) &&
        Objects.equals(this.desinationQueue, ptsV2PaymentsPost201ResponseRiskInformationProfile.desinationQueue) &&
        Objects.equals(this.selectorRule, ptsV2PaymentsPost201ResponseRiskInformationProfile.selectorRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, desinationQueue, selectorRule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtsV2PaymentsPost201ResponseRiskInformationProfile {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    desinationQueue: ").append(toIndentedString(desinationQueue)).append("\n");
    sb.append("    selectorRule: ").append(toIndentedString(selectorRule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

