/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Fee Funding Section
 */
@JsonPropertyOrder({
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_REQUEST_ID,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_INTERCHANGE_PER_ITEM_FEE,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_INTERCHANGE_DESCRIPTION,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_INTERCHANGE_PERCENTAGE,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_INTERCHANGE_PERCENTAGE_AMOUNT,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_DISCOUNT_PERCENTAGE,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_DISCOUNT_AMOUNT,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_DISCOUNT_PER_ITEM_FEE,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_TOTAL_FEE,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_FEE_CURRENCY,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_DUES_ASSESSMENTS,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_FUNDING_AMOUNT,
  ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.JSON_PROPERTY_FUNDING_CURRENCY
})
@JsonTypeName("reportingV3PurchaseRefundDetailsGet200Response_feeAndFundingDetails_inner")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner {
  public static final String JSON_PROPERTY_REQUEST_ID = "requestId";
  private String requestId;

  public static final String JSON_PROPERTY_INTERCHANGE_PER_ITEM_FEE = "interchangePerItemFee";
  private String interchangePerItemFee;

  public static final String JSON_PROPERTY_INTERCHANGE_DESCRIPTION = "interchangeDescription";
  private String interchangeDescription;

  public static final String JSON_PROPERTY_INTERCHANGE_PERCENTAGE = "interchangePercentage";
  private String interchangePercentage;

  public static final String JSON_PROPERTY_INTERCHANGE_PERCENTAGE_AMOUNT = "interchangePercentageAmount";
  private String interchangePercentageAmount;

  public static final String JSON_PROPERTY_DISCOUNT_PERCENTAGE = "discountPercentage";
  private String discountPercentage;

  public static final String JSON_PROPERTY_DISCOUNT_AMOUNT = "discountAmount";
  private String discountAmount;

  public static final String JSON_PROPERTY_DISCOUNT_PER_ITEM_FEE = "discountPerItemFee";
  private String discountPerItemFee;

  public static final String JSON_PROPERTY_TOTAL_FEE = "totalFee";
  private String totalFee;

  public static final String JSON_PROPERTY_FEE_CURRENCY = "feeCurrency";
  private String feeCurrency;

  public static final String JSON_PROPERTY_DUES_ASSESSMENTS = "duesAssessments";
  private String duesAssessments;

  public static final String JSON_PROPERTY_FUNDING_AMOUNT = "fundingAmount";
  private String fundingAmount;

  public static final String JSON_PROPERTY_FUNDING_CURRENCY = "fundingCurrency";
  private String fundingCurrency;

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner() {
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner requestId(String requestId) {
    
    this.requestId = requestId;
    return this;
  }

  /**
   * An unique identification number assigned by CyberSource to identify the submitted request.
   * @return requestId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner interchangePerItemFee(String interchangePerItemFee) {
    
    this.interchangePerItemFee = interchangePerItemFee;
    return this;
  }

  /**
   * interchange Per Item Fee
   * @return interchangePerItemFee
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERCHANGE_PER_ITEM_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInterchangePerItemFee() {
    return interchangePerItemFee;
  }


  @JsonProperty(JSON_PROPERTY_INTERCHANGE_PER_ITEM_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterchangePerItemFee(String interchangePerItemFee) {
    this.interchangePerItemFee = interchangePerItemFee;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner interchangeDescription(String interchangeDescription) {
    
    this.interchangeDescription = interchangeDescription;
    return this;
  }

  /**
   * interchange Description
   * @return interchangeDescription
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERCHANGE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInterchangeDescription() {
    return interchangeDescription;
  }


  @JsonProperty(JSON_PROPERTY_INTERCHANGE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterchangeDescription(String interchangeDescription) {
    this.interchangeDescription = interchangeDescription;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner interchangePercentage(String interchangePercentage) {
    
    this.interchangePercentage = interchangePercentage;
    return this;
  }

  /**
   * interchange Percentage
   * @return interchangePercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERCHANGE_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInterchangePercentage() {
    return interchangePercentage;
  }


  @JsonProperty(JSON_PROPERTY_INTERCHANGE_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterchangePercentage(String interchangePercentage) {
    this.interchangePercentage = interchangePercentage;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner interchangePercentageAmount(String interchangePercentageAmount) {
    
    this.interchangePercentageAmount = interchangePercentageAmount;
    return this;
  }

  /**
   * interchange Percentage Amount
   * @return interchangePercentageAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERCHANGE_PERCENTAGE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInterchangePercentageAmount() {
    return interchangePercentageAmount;
  }


  @JsonProperty(JSON_PROPERTY_INTERCHANGE_PERCENTAGE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterchangePercentageAmount(String interchangePercentageAmount) {
    this.interchangePercentageAmount = interchangePercentageAmount;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner discountPercentage(String discountPercentage) {
    
    this.discountPercentage = discountPercentage;
    return this;
  }

  /**
   * Discount Percentage
   * @return discountPercentage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCOUNT_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDiscountPercentage() {
    return discountPercentage;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountPercentage(String discountPercentage) {
    this.discountPercentage = discountPercentage;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner discountAmount(String discountAmount) {
    
    this.discountAmount = discountAmount;
    return this;
  }

  /**
   * Discount Amount
   * @return discountAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCOUNT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDiscountAmount() {
    return discountAmount;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountAmount(String discountAmount) {
    this.discountAmount = discountAmount;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner discountPerItemFee(String discountPerItemFee) {
    
    this.discountPerItemFee = discountPerItemFee;
    return this;
  }

  /**
   * Discount Per Item Fee
   * @return discountPerItemFee
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCOUNT_PER_ITEM_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDiscountPerItemFee() {
    return discountPerItemFee;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT_PER_ITEM_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountPerItemFee(String discountPerItemFee) {
    this.discountPerItemFee = discountPerItemFee;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner totalFee(String totalFee) {
    
    this.totalFee = totalFee;
    return this;
  }

  /**
   * Total Fee
   * @return totalFee
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTotalFee() {
    return totalFee;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalFee(String totalFee) {
    this.totalFee = totalFee;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner feeCurrency(String feeCurrency) {
    
    this.feeCurrency = feeCurrency;
    return this;
  }

  /**
   * Fee Currency
   * @return feeCurrency
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FEE_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFeeCurrency() {
    return feeCurrency;
  }


  @JsonProperty(JSON_PROPERTY_FEE_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeeCurrency(String feeCurrency) {
    this.feeCurrency = feeCurrency;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner duesAssessments(String duesAssessments) {
    
    this.duesAssessments = duesAssessments;
    return this;
  }

  /**
   * Dues Assessments
   * @return duesAssessments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DUES_ASSESSMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDuesAssessments() {
    return duesAssessments;
  }


  @JsonProperty(JSON_PROPERTY_DUES_ASSESSMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuesAssessments(String duesAssessments) {
    this.duesAssessments = duesAssessments;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner fundingAmount(String fundingAmount) {
    
    this.fundingAmount = fundingAmount;
    return this;
  }

  /**
   * Funding Amount
   * @return fundingAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNDING_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFundingAmount() {
    return fundingAmount;
  }


  @JsonProperty(JSON_PROPERTY_FUNDING_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFundingAmount(String fundingAmount) {
    this.fundingAmount = fundingAmount;
  }

  public ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner fundingCurrency(String fundingCurrency) {
    
    this.fundingCurrency = fundingCurrency;
    return this;
  }

  /**
   * Funding Currency (ISO 4217)
   * @return fundingCurrency
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNDING_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFundingCurrency() {
    return fundingCurrency;
  }


  @JsonProperty(JSON_PROPERTY_FUNDING_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFundingCurrency(String fundingCurrency) {
    this.fundingCurrency = fundingCurrency;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner = (ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner) o;
    return Objects.equals(this.requestId, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.requestId) &&
        Objects.equals(this.interchangePerItemFee, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.interchangePerItemFee) &&
        Objects.equals(this.interchangeDescription, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.interchangeDescription) &&
        Objects.equals(this.interchangePercentage, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.interchangePercentage) &&
        Objects.equals(this.interchangePercentageAmount, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.interchangePercentageAmount) &&
        Objects.equals(this.discountPercentage, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.discountPercentage) &&
        Objects.equals(this.discountAmount, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.discountAmount) &&
        Objects.equals(this.discountPerItemFee, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.discountPerItemFee) &&
        Objects.equals(this.totalFee, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.totalFee) &&
        Objects.equals(this.feeCurrency, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.feeCurrency) &&
        Objects.equals(this.duesAssessments, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.duesAssessments) &&
        Objects.equals(this.fundingAmount, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.fundingAmount) &&
        Objects.equals(this.fundingCurrency, reportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner.fundingCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, interchangePerItemFee, interchangeDescription, interchangePercentage, interchangePercentageAmount, discountPercentage, discountAmount, discountPerItemFee, totalFee, feeCurrency, duesAssessments, fundingAmount, fundingCurrency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportingV3PurchaseRefundDetailsGet200ResponseFeeAndFundingDetailsInner {\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    interchangePerItemFee: ").append(toIndentedString(interchangePerItemFee)).append("\n");
    sb.append("    interchangeDescription: ").append(toIndentedString(interchangeDescription)).append("\n");
    sb.append("    interchangePercentage: ").append(toIndentedString(interchangePercentage)).append("\n");
    sb.append("    interchangePercentageAmount: ").append(toIndentedString(interchangePercentageAmount)).append("\n");
    sb.append("    discountPercentage: ").append(toIndentedString(discountPercentage)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    discountPerItemFee: ").append(toIndentedString(discountPerItemFee)).append("\n");
    sb.append("    totalFee: ").append(toIndentedString(totalFee)).append("\n");
    sb.append("    feeCurrency: ").append(toIndentedString(feeCurrency)).append("\n");
    sb.append("    duesAssessments: ").append(toIndentedString(duesAssessments)).append("\n");
    sb.append("    fundingAmount: ").append(toIndentedString(fundingAmount)).append("\n");
    sb.append("    fundingCurrency: ").append(toIndentedString(fundingCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

