/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ReportingV3ChargebackSummariesGet200ResponseChargebackSummariesInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ReportingV3ChargebackSummariesGet200Response
 */
@JsonPropertyOrder({
  ReportingV3ChargebackSummariesGet200Response.JSON_PROPERTY_ORGANIZATION_ID,
  ReportingV3ChargebackSummariesGet200Response.JSON_PROPERTY_START_TIME,
  ReportingV3ChargebackSummariesGet200Response.JSON_PROPERTY_END_TIME,
  ReportingV3ChargebackSummariesGet200Response.JSON_PROPERTY_CHARGEBACK_SUMMARIES
})
@JsonTypeName("reportingV3ChargebackSummariesGet200Response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T18:32:10.370382+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class ReportingV3ChargebackSummariesGet200Response {
  public static final String JSON_PROPERTY_ORGANIZATION_ID = "organizationId";
  private String organizationId;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  private String endTime;

  public static final String JSON_PROPERTY_CHARGEBACK_SUMMARIES = "chargebackSummaries";
  private List<ReportingV3ChargebackSummariesGet200ResponseChargebackSummariesInner> chargebackSummaries = new ArrayList<>();

  public ReportingV3ChargebackSummariesGet200Response() {
  }

  public ReportingV3ChargebackSummariesGet200Response organizationId(String organizationId) {
    
    this.organizationId = organizationId;
    return this;
  }

  /**
   * Organization Id
   * @return organizationId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrganizationId() {
    return organizationId;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  public ReportingV3ChargebackSummariesGet200Response startTime(OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

  /**
   * Report Start Date
   * @return startTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public ReportingV3ChargebackSummariesGet200Response endTime(String endTime) {
    
    this.endTime = endTime;
    return this;
  }

  /**
   * Report Start Date
   * @return endTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndTime() {
    return endTime;
  }


  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  public ReportingV3ChargebackSummariesGet200Response chargebackSummaries(List<ReportingV3ChargebackSummariesGet200ResponseChargebackSummariesInner> chargebackSummaries) {
    
    this.chargebackSummaries = chargebackSummaries;
    return this;
  }

  public ReportingV3ChargebackSummariesGet200Response addChargebackSummariesItem(ReportingV3ChargebackSummariesGet200ResponseChargebackSummariesInner chargebackSummariesItem) {
    if (this.chargebackSummaries == null) {
      this.chargebackSummaries = new ArrayList<>();
    }
    this.chargebackSummaries.add(chargebackSummariesItem);
    return this;
  }

  /**
   * List of Summary values
   * @return chargebackSummaries
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHARGEBACK_SUMMARIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ReportingV3ChargebackSummariesGet200ResponseChargebackSummariesInner> getChargebackSummaries() {
    return chargebackSummaries;
  }


  @JsonProperty(JSON_PROPERTY_CHARGEBACK_SUMMARIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargebackSummaries(List<ReportingV3ChargebackSummariesGet200ResponseChargebackSummariesInner> chargebackSummaries) {
    this.chargebackSummaries = chargebackSummaries;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportingV3ChargebackSummariesGet200Response reportingV3ChargebackSummariesGet200Response = (ReportingV3ChargebackSummariesGet200Response) o;
    return Objects.equals(this.organizationId, reportingV3ChargebackSummariesGet200Response.organizationId) &&
        Objects.equals(this.startTime, reportingV3ChargebackSummariesGet200Response.startTime) &&
        Objects.equals(this.endTime, reportingV3ChargebackSummariesGet200Response.endTime) &&
        Objects.equals(this.chargebackSummaries, reportingV3ChargebackSummariesGet200Response.chargebackSummaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organizationId, startTime, endTime, chargebackSummaries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportingV3ChargebackSummariesGet200Response {\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    chargebackSummaries: ").append(toIndentedString(chargebackSummaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

