/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner
 */
@JsonPropertyOrder({
  ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner.JSON_PROPERTY_TIME,
  ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner.JSON_PROPERTY_ADDED_BY,
  ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner.JSON_PROPERTY_COMMENTS
})
@JsonTypeName("reportingV3ConversionDetailsGet200Response_conversionDetails_inner_notes_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T18:32:10.370382+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner {
  public static final String JSON_PROPERTY_TIME = "time";
  private OffsetDateTime time;

  public static final String JSON_PROPERTY_ADDED_BY = "addedBy";
  private String addedBy;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  private String comments;

  public ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner() {
  }

  public ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner time(OffsetDateTime time) {
    
    this.time = time;
    return this;
  }

  /**
   * Time of the note added by reviewer
   * @return time
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(OffsetDateTime time) {
    this.time = time;
  }

  public ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner addedBy(String addedBy) {
    
    this.addedBy = addedBy;
    return this;
  }

  /**
   * Note added by reviewer
   * @return addedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddedBy() {
    return addedBy;
  }


  @JsonProperty(JSON_PROPERTY_ADDED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddedBy(String addedBy) {
    this.addedBy = addedBy;
  }

  public ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner comments(String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Comments given by the reviewer
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(String comments) {
    this.comments = comments;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner reportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner = (ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner) o;
    return Objects.equals(this.time, reportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner.time) &&
        Objects.equals(this.addedBy, reportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner.addedBy) &&
        Objects.equals(this.comments, reportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner.comments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, addedBy, comments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportingV3ConversionDetailsGet200ResponseConversionDetailsInnerNotesInner {\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    addedBy: ").append(toIndentedString(addedBy)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

