/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ReportingV3NetFundingsGet200ResponseTotalPurchasesInner
 */
@JsonPropertyOrder({
  ReportingV3NetFundingsGet200ResponseTotalPurchasesInner.JSON_PROPERTY_CURRENCY,
  ReportingV3NetFundingsGet200ResponseTotalPurchasesInner.JSON_PROPERTY_VALUE
})
@JsonTypeName("reportingV3NetFundingsGet200Response_totalPurchases_inner")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class ReportingV3NetFundingsGet200ResponseTotalPurchasesInner {
  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_VALUE = "value";
  private String value;

  public ReportingV3NetFundingsGet200ResponseTotalPurchasesInner() {
  }

  public ReportingV3NetFundingsGet200ResponseTotalPurchasesInner currency(String currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Valid ISO 4217 ALPHA-3 currency code
   * @return currency
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public ReportingV3NetFundingsGet200ResponseTotalPurchasesInner value(String value) {
    
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(String value) {
    this.value = value;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportingV3NetFundingsGet200ResponseTotalPurchasesInner reportingV3NetFundingsGet200ResponseTotalPurchasesInner = (ReportingV3NetFundingsGet200ResponseTotalPurchasesInner) o;
    return Objects.equals(this.currency, reportingV3NetFundingsGet200ResponseTotalPurchasesInner.currency) &&
        Objects.equals(this.value, reportingV3NetFundingsGet200ResponseTotalPurchasesInner.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportingV3NetFundingsGet200ResponseTotalPurchasesInner {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

