/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.PtsV2IncrementalAuthorizationPatch201ResponseLinks;
import org.openapitools.client.model.RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation;
import org.openapitools.client.model.RiskV1AuthenticationSetupsPost201ResponseErrorInformation;
import org.openapitools.client.model.RiskV1DecisionsPost201ResponseClientReferenceInformation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RiskV1AuthenticationSetupsPost201Response
 */
@JsonPropertyOrder({
  RiskV1AuthenticationSetupsPost201Response.JSON_PROPERTY_LINKS,
  RiskV1AuthenticationSetupsPost201Response.JSON_PROPERTY_ID,
  RiskV1AuthenticationSetupsPost201Response.JSON_PROPERTY_SUBMIT_TIME_UTC,
  RiskV1AuthenticationSetupsPost201Response.JSON_PROPERTY_STATUS,
  RiskV1AuthenticationSetupsPost201Response.JSON_PROPERTY_CONSUMER_AUTHENTICATION_INFORMATION,
  RiskV1AuthenticationSetupsPost201Response.JSON_PROPERTY_CLIENT_REFERENCE_INFORMATION,
  RiskV1AuthenticationSetupsPost201Response.JSON_PROPERTY_ERROR_INFORMATION
})
@JsonTypeName("riskV1AuthenticationSetupsPost201Response")
//@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T19:17:21.826843+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class RiskV1AuthenticationSetupsPost201Response {
  public static final String JSON_PROPERTY_LINKS = "_links";
  private PtsV2IncrementalAuthorizationPatch201ResponseLinks links;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_SUBMIT_TIME_UTC = "submitTimeUtc";
  private String submitTimeUtc;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_CONSUMER_AUTHENTICATION_INFORMATION = "consumerAuthenticationInformation";
  private RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation consumerAuthenticationInformation;

  public static final String JSON_PROPERTY_CLIENT_REFERENCE_INFORMATION = "clientReferenceInformation";
  private RiskV1DecisionsPost201ResponseClientReferenceInformation clientReferenceInformation;

  public static final String JSON_PROPERTY_ERROR_INFORMATION = "errorInformation";
  private RiskV1AuthenticationSetupsPost201ResponseErrorInformation errorInformation;

  public RiskV1AuthenticationSetupsPost201Response() {
  }

  public RiskV1AuthenticationSetupsPost201Response links(PtsV2IncrementalAuthorizationPatch201ResponseLinks links) {
    
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PtsV2IncrementalAuthorizationPatch201ResponseLinks getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(PtsV2IncrementalAuthorizationPatch201ResponseLinks links) {
    this.links = links;
  }

  public RiskV1AuthenticationSetupsPost201Response id(String id) {
    
    this.id = id;
    return this;
  }

  /**
   * An unique identification number generated by Cybersource to identify the submitted request. Returned by all services. It is also appended to the endpoint of the resource. On incremental authorizations, this value with be the same as the identification number returned in the original authorization response. 
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }

  public RiskV1AuthenticationSetupsPost201Response submitTimeUtc(String submitTimeUtc) {
    
    this.submitTimeUtc = submitTimeUtc;
    return this;
  }

  /**
   * Time of request in UTC. Format: &#x60;YYYY-MM-DDThh:mm:ssZ&#x60; **Example** &#x60;2016-08-11T22:47:57Z&#x60; equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The &#x60;T&#x60; separates the date and the time. The &#x60;Z&#x60; indicates UTC.  Returned by Cybersource for all services. 
   * @return submitTimeUtc
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBMIT_TIME_UTC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubmitTimeUtc() {
    return submitTimeUtc;
  }


  @JsonProperty(JSON_PROPERTY_SUBMIT_TIME_UTC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubmitTimeUtc(String submitTimeUtc) {
    this.submitTimeUtc = submitTimeUtc;
  }

  public RiskV1AuthenticationSetupsPost201Response status(String status) {
    
    this.status = status;
    return this;
  }

  /**
   * The status for payerAuthentication 201 setup calls. Possible value is: - COMPLETED - FAILED 
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }

  public RiskV1AuthenticationSetupsPost201Response consumerAuthenticationInformation(RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation consumerAuthenticationInformation) {
    
    this.consumerAuthenticationInformation = consumerAuthenticationInformation;
    return this;
  }

  /**
   * Get consumerAuthenticationInformation
   * @return consumerAuthenticationInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONSUMER_AUTHENTICATION_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation getConsumerAuthenticationInformation() {
    return consumerAuthenticationInformation;
  }


  @JsonProperty(JSON_PROPERTY_CONSUMER_AUTHENTICATION_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConsumerAuthenticationInformation(RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation consumerAuthenticationInformation) {
    this.consumerAuthenticationInformation = consumerAuthenticationInformation;
  }

  public RiskV1AuthenticationSetupsPost201Response clientReferenceInformation(RiskV1DecisionsPost201ResponseClientReferenceInformation clientReferenceInformation) {
    
    this.clientReferenceInformation = clientReferenceInformation;
    return this;
  }

  /**
   * Get clientReferenceInformation
   * @return clientReferenceInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_REFERENCE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RiskV1DecisionsPost201ResponseClientReferenceInformation getClientReferenceInformation() {
    return clientReferenceInformation;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_REFERENCE_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientReferenceInformation(RiskV1DecisionsPost201ResponseClientReferenceInformation clientReferenceInformation) {
    this.clientReferenceInformation = clientReferenceInformation;
  }

  public RiskV1AuthenticationSetupsPost201Response errorInformation(RiskV1AuthenticationSetupsPost201ResponseErrorInformation errorInformation) {
    
    this.errorInformation = errorInformation;
    return this;
  }

  /**
   * Get errorInformation
   * @return errorInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RiskV1AuthenticationSetupsPost201ResponseErrorInformation getErrorInformation() {
    return errorInformation;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorInformation(RiskV1AuthenticationSetupsPost201ResponseErrorInformation errorInformation) {
    this.errorInformation = errorInformation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskV1AuthenticationSetupsPost201Response riskV1AuthenticationSetupsPost201Response = (RiskV1AuthenticationSetupsPost201Response) o;
    return Objects.equals(this.links, riskV1AuthenticationSetupsPost201Response.links) &&
        Objects.equals(this.id, riskV1AuthenticationSetupsPost201Response.id) &&
        Objects.equals(this.submitTimeUtc, riskV1AuthenticationSetupsPost201Response.submitTimeUtc) &&
        Objects.equals(this.status, riskV1AuthenticationSetupsPost201Response.status) &&
        Objects.equals(this.consumerAuthenticationInformation, riskV1AuthenticationSetupsPost201Response.consumerAuthenticationInformation) &&
        Objects.equals(this.clientReferenceInformation, riskV1AuthenticationSetupsPost201Response.clientReferenceInformation) &&
        Objects.equals(this.errorInformation, riskV1AuthenticationSetupsPost201Response.errorInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, id, submitTimeUtc, status, consumerAuthenticationInformation, clientReferenceInformation, errorInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskV1AuthenticationSetupsPost201Response {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    submitTimeUtc: ").append(toIndentedString(submitTimeUtc)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    consumerAuthenticationInformation: ").append(toIndentedString(consumerAuthenticationInformation)).append("\n");
    sb.append("    clientReferenceInformation: ").append(toIndentedString(clientReferenceInformation)).append("\n");
    sb.append("    errorInformation: ").append(toIndentedString(errorInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

