/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TssV2TransactionsGet200ResponseRecurringPaymentInformation
 */
@JsonPropertyOrder({
  TssV2TransactionsGet200ResponseRecurringPaymentInformation.JSON_PROPERTY_AMOUNT_TYPE
})
@JsonTypeName("tssV2TransactionsGet200Response_recurringPaymentInformation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T18:32:10.370382+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class TssV2TransactionsGet200ResponseRecurringPaymentInformation {
  public static final String JSON_PROPERTY_AMOUNT_TYPE = "amountType";
  private String amountType;

  public TssV2TransactionsGet200ResponseRecurringPaymentInformation() {
  }

  public TssV2TransactionsGet200ResponseRecurringPaymentInformation amountType(String amountType) {
    
    this.amountType = amountType;
    return this;
  }

  /**
   * Indicates recurring amount type agreed by the cardholder Valid Values : 1- Fixed amount recurring payment 2- Recurring payment with maximum amount 
   * @return amountType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAmountType() {
    return amountType;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmountType(String amountType) {
    this.amountType = amountType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TssV2TransactionsGet200ResponseRecurringPaymentInformation tssV2TransactionsGet200ResponseRecurringPaymentInformation = (TssV2TransactionsGet200ResponseRecurringPaymentInformation) o;
    return Objects.equals(this.amountType, tssV2TransactionsGet200ResponseRecurringPaymentInformation.amountType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TssV2TransactionsGet200ResponseRecurringPaymentInformation {\n");
    sb.append("    amountType: ").append(toIndentedString(amountType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

