/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TssV2TransactionsGet200ResponseInstallmentInformation
 */
@JsonPropertyOrder({
  TssV2TransactionsGet200ResponseInstallmentInformation.JSON_PROPERTY_NUMBER_OF_INSTALLMENTS,
  TssV2TransactionsGet200ResponseInstallmentInformation.JSON_PROPERTY_IDENTIFIER
})
@JsonTypeName("tssV2TransactionsGet200Response_installmentInformation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T18:32:10.370382+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class TssV2TransactionsGet200ResponseInstallmentInformation {
  public static final String JSON_PROPERTY_NUMBER_OF_INSTALLMENTS = "numberOfInstallments";
  private String numberOfInstallments;

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  private String identifier;

  public TssV2TransactionsGet200ResponseInstallmentInformation() {
  }

  public TssV2TransactionsGet200ResponseInstallmentInformation numberOfInstallments(String numberOfInstallments) {
    
    this.numberOfInstallments = numberOfInstallments;
    return this;
  }

  /**
   * Number of Installments.
   * @return numberOfInstallments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_INSTALLMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNumberOfInstallments() {
    return numberOfInstallments;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_OF_INSTALLMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberOfInstallments(String numberOfInstallments) {
    this.numberOfInstallments = numberOfInstallments;
  }

  public TssV2TransactionsGet200ResponseInstallmentInformation identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

  /**
   * Standing Instruction/Installment identifier. 
   * @return identifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TssV2TransactionsGet200ResponseInstallmentInformation tssV2TransactionsGet200ResponseInstallmentInformation = (TssV2TransactionsGet200ResponseInstallmentInformation) o;
    return Objects.equals(this.numberOfInstallments, tssV2TransactionsGet200ResponseInstallmentInformation.numberOfInstallments) &&
        Objects.equals(this.identifier, tssV2TransactionsGet200ResponseInstallmentInformation.identifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfInstallments, identifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TssV2TransactionsGet200ResponseInstallmentInformation {\n");
    sb.append("    numberOfInstallments: ").append(toIndentedString(numberOfInstallments)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

