/*
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.UpdateInvoiceSettingsRequestInvoiceSettingsInformation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateInvoiceSettingsRequest
 */
@JsonPropertyOrder({
  UpdateInvoiceSettingsRequest.JSON_PROPERTY_INVOICE_SETTINGS_INFORMATION
})
@JsonTypeName("updateInvoiceSettings_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-09T18:32:10.370382+07:00[Asia/Bangkok]", comments = "Generator version: 7.9.0")
public class UpdateInvoiceSettingsRequest {
  public static final String JSON_PROPERTY_INVOICE_SETTINGS_INFORMATION = "invoiceSettingsInformation";
  private UpdateInvoiceSettingsRequestInvoiceSettingsInformation invoiceSettingsInformation;

  public UpdateInvoiceSettingsRequest() {
  }

  public UpdateInvoiceSettingsRequest invoiceSettingsInformation(UpdateInvoiceSettingsRequestInvoiceSettingsInformation invoiceSettingsInformation) {
    
    this.invoiceSettingsInformation = invoiceSettingsInformation;
    return this;
  }

  /**
   * Get invoiceSettingsInformation
   * @return invoiceSettingsInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVOICE_SETTINGS_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateInvoiceSettingsRequestInvoiceSettingsInformation getInvoiceSettingsInformation() {
    return invoiceSettingsInformation;
  }


  @JsonProperty(JSON_PROPERTY_INVOICE_SETTINGS_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvoiceSettingsInformation(UpdateInvoiceSettingsRequestInvoiceSettingsInformation invoiceSettingsInformation) {
    this.invoiceSettingsInformation = invoiceSettingsInformation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateInvoiceSettingsRequest updateInvoiceSettingsRequest = (UpdateInvoiceSettingsRequest) o;
    return Objects.equals(this.invoiceSettingsInformation, updateInvoiceSettingsRequest.invoiceSettingsInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invoiceSettingsInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateInvoiceSettingsRequest {\n");
    sb.append("    invoiceSettingsInformation: ").append(toIndentedString(invoiceSettingsInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

